set(ARCANE_SOURCES
  ArcaneHdf5Global.h
  ArcaneHdf5Registerer.cc
  ArcaneHdf5Registerer.h
  Hdf5Utils.cc
  Hdf5Utils.h
  Hdf5VariableInfoBase.cc
  Hdf5VariableInfoBase.h
  Hdf5ReaderWriter.cc
  Hdf5ReaderWriter.h
  Hdf5VariableReader.cc
  Hdf5VariableWriter.cc
  Hdf5MpiReaderWriter.cc
  Hdf5MpiReaderWriter.h
  VtkHdfPostProcessor.cc
  VtkHdfV2PostProcessor.cc
)

set(AXL_FILES
  Hdf5ReaderWriter
  Hdf5VariableReader
  Hdf5VariableWriter
  Hdf5MpiReaderWriter
  VtkHdfPostProcessor
  VtkHdfV2PostProcessor
)
