// -*- C++ -*-
/* Author : havep at Tue Aug 21 10:46:13 2012
 * Generated by createNew
 */

#ifndef MULTIPLICATIVEFIELDSPLITSERVICE_H
#define MULTIPLICATIVEFIELDSPLITSERVICE_H
/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#include <ALIEN/Kernels/PETSc/PETScPrecomp.h>
#include <ALIEN/AlienExternalPackagesPrecomp.h>

#include <ALIEN/Kernels/PETSc/LinearSolver/PETScConfig.h>
#include <ALIEN/Kernels/PETSc/LinearSolver/FieldSplit/IFieldSplitType.h>
#include <ALIEN/axl/MultiplicativeFieldSplitType_axl.h>

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

namespace Alien {

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

class ALIEN_EXTERNAL_PACKAGES_EXPORT MultiplicativeFieldSplitTypeService
: public ArcaneMultiplicativeFieldSplitTypeObject,
  public PETScConfig
{
 public:
#ifdef ALIEN_USE_ARCANE
  MultiplicativeFieldSplitTypeService(const Arcane::ServiceBuildInfo & sbi) ;
#endif

  MultiplicativeFieldSplitTypeService(
      Arccore::MessagePassing::IMessagePassingMng* parallel_mng,
      std::shared_ptr<IOptionsMultiplicativeFieldSplitType> options);

  ~MultiplicativeFieldSplitTypeService() {}
  
public:
 //! Configure FieldSplit type
 Arccore::Integer configure(PC& pc, const Arccore::Integer nbField);
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

} // namespace Alien

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/
#endif //MULTIPLICATIVEFIELDSPLITSERVICE_H
