set(ARCANE_SOURCES
  AlephCudaVector.cc
  AlephCudaVector.h
  AlephCudaMatrix.cc
  AlephCudaMatrix.h
  AlephCuda.cc
  AlephCuda.h
  AlephCudaVector.h
  AlephCudaMatrix.h
  AlephCuda.h
  IAlephCuda.h
  AlephCudaVector.h
  AlephCudaMatrix.h
  AlephCudaMatrixCrs.h
)
