// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
#ifndef CONSTANTFLOWMODELSERVICE_H
#define CONSTANTFLOWMODELSERVICE_H
/* Author : haeberlf at Fri Aug 29 14:29:07 2008
 * Generated by createNew
 */

#include "Flow/FlowNumericalModel/IFlowNumericalModel.h"

#include <arcane/VariableTypes.h>
#include <arcane/VariableTypedef.h>

#include "Mesh/Geometry/IGeometryMng.h"

namespace Arcane { }
using namespace Arcane;

#include "ConstantFlowModel_axl.h"

class ConstantFlowModelService :
  public ArcaneConstantFlowModelObject
{
public:
  /** Constructeur de la classe */
  ConstantFlowModelService(const Arcane::ServiceBuildInfo & sbi) :
    ArcaneConstantFlowModelObject(sbi)
    {
      ;
    }

  /** Destructeur de la classe */
  virtual ~ConstantFlowModelService() {}

public:

  //! Initialisation
  void init();

  //! Apply service function
  void apply();

  //! Prepare
  void prepare();

private:

  Real3 m_velocity;

  // Geometry Service
  IGeometryMng* m_geometry_service;

};

#endif /* CONSTANTFLOWMODELSERVICE_H */
