set(ARCANE_SOURCES
  RayMeshIntersectionUnitTest.cc
  MaterialHeatTestModule.cc
  MeshMaterialTesterModule.cc
  CartesianMeshTesterModule.cc
  HyodaMixedCellsUnitTest.cc
  GeometricUnitTest.cc
  MeshMaterialSyncUnitTest.cc
  MeshMaterialSimdUnitTest.cc
  AMRCartesianMeshTesterModule.cc
  CartesianMeshTestUtils.cc
  CartesianMeshTestUtils.h
  CartesianMeshV2TestUtils.cc
  CartesianMeshV2TestUtils.h
  UnitTestCartesianMeshPatch.cc
  IMaterialEquationOfState.h
)

set(AXL_FILES 
  RayMeshIntersectionUnitTest
  MaterialHeatTest
  MeshMaterialTester
  CartesianMeshTester
  AdiProjection
  HyodaMixedCellsUnitTest
  GeometricUnitTest
  MeshMaterialSyncUnitTest
  AMRCartesianMeshTester
  UnitTestCartesianMeshPatch
)
