// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2023 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
/*---------------------------------------------------------------------------*/
/* VariableSynchronizerEventArgs.h                             (C) 2000-2023 */
/*                                                                           */
/* Arguments for events generated by IVariableSynchronizer.                  */
/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/
#ifndef ARCANE_VARIABLESYNCHRONIZEREVENTARGS_H
#define ARCANE_VARIABLESYNCHRONIZEREVENTARGS_H
/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#include "arcane/utils/UtilsTypes.h"
#include "arcane/utils/Array.h"

#include "arcane/core/ArcaneTypes.h"

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

namespace Arcane
{

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

/*!
 * \brief Arguments for the event notifying a variable synchronization.
 *
 * Instances of this class can be used multiple times.
 * You must call initialize() to initialize or reset the instance
 * with default values.
 */
class ARCANE_CORE_EXPORT VariableSynchronizerEventArgs
{
 public:

  //! Enum to know if we are at the beginning or the end of the synchronization
  enum class State
  {
    BeginSynchronize,
    EndSynchronize
  };

  //! Comparison of phantom entity values before/after a synchronization
  enum class CompareStatus
  {
    //! No comparison or unknown result
    Unknown,
    //! Same values before and after synchronization
    Same,
    //! Different values before and after synchronization
    Different
  };

 public:

  ARCANE_DEPRECATED_REASON("Y2023: Use VariableSynchronizerEventArgs(IVariableSynchronizer* vs) and call initialize() instead")
  VariableSynchronizerEventArgs(VariableCollection vars, IVariableSynchronizer* vs,
                                Real elapsed_time, State state = State::EndSynchronize);
  ARCANE_DEPRECATED_REASON("Y2023: Use VariableSynchronizerEventArgs(IVariableSynchronizer* vs) and call initialize() instead")
  VariableSynchronizerEventArgs(IVariable* var, IVariableSynchronizer* vs,
                                Real elapsed_time, State state = State::EndSynchronize);

  ARCANE_DEPRECATED_REASON("Y2023: Use VariableSynchronizerEventArgs(IVariableSynchronizer* vs) and call initialize() instead")
  VariableSynchronizerEventArgs(VariableCollection vars, IVariableSynchronizer* vs);

  ARCANE_DEPRECATED_REASON("Y2023: Use VariableSynchronizerEventArgs(IVariableSynchronizer* vs) and call initialize() instead")
  VariableSynchronizerEventArgs(IVariable* var, IVariableSynchronizer* vs);

  VariableSynchronizerEventArgs(IVariableSynchronizer* vs)
  : m_var_syncer(vs)
  {}

 public:

  void initialize(const VariableCollection& vars);
  void initialize(IVariable* var);

  //! Associated synchronizer.
  IVariableSynchronizer* synchronizer() const { return m_var_syncer; }

  //! List of synchronized variables.
  ConstArrayView<IVariable*> variables() const;

  /*!
   * \brief List of comparison status.
   *
   * The value of the i-th element of compareStatus() indicates the state
   * of comparison for the i-th variable in variables().
   *
   * This list is only valid for end synchronization events
   * (state()==State::EndSynchronize).
   */
  ConstArrayView<CompareStatus> compareStatusList() const { return m_compare_status_list; }

  //! Sets the comparison status of the i-th variable.
  void setCompareStatus(Int32 i, CompareStatus v) { m_compare_status_list[i] = v; }

  //! Time spent in synchronization.
  Real elapsedTime() const { return m_elapsed_time; }
  void setElapsedTime(Real v) { m_elapsed_time = v; }

  //! Indicator of the event moment
  State state() const { return m_state; }
  void setState(State v) { m_state = v; }

 private:

  IVariableSynchronizer* m_var_syncer = nullptr;
  UniqueArray<IVariable*> m_variables;
  UniqueArray<CompareStatus> m_compare_status_list;
  Real m_elapsed_time = 0.0;
  State m_state = State::BeginSynchronize;

 private:

  void _reset();
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

} // namespace Arcane

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif
