
# Macro pour ajouter récursivement à '_ALLLIBS' les bibliothèques
# 'lib' et ses dépendances en se basant sur la valeur de ${lib}_DEPENDS
set(_ALLLIBS)
set(_DONE_TARGETS)
macro(arcane_vtkutils_add_depend_lib_to_list lib)
  if (TARGET ${lib})
    list(FIND _DONE_TARGETS ${lib} _IDX)
    if (${_IDX} EQUAL -1)
      list(APPEND _DONE_TARGETS ${lib})
      #message(STATUS "ADD_DEPEND_LIB_TO_LIST LIB=${lib}")
      get_target_property(_LOC1 ${lib} LOCATION)
      #message(STATUS "  LOCATION=${_LOC1}")
      list(APPEND _ALLLIBS ${_LOC1})
      #message(STATUS " DEPENDS = ${${lib}_DEPENDS}")
      foreach(sublib ${${lib}_DEPENDS})
        arcane_vtkutils_add_depend_lib_to_list(${sublib})
      endforeach()
    endif()
  endif()
endmacro()

# Version v2 de la macro pour prendre en compte les changements à partir de la v9 de vtk
macro(arcane_vtkutils_add_depend_lib_to_list_v2 lib)
  if (TARGET ${lib})
    list(FIND _DONE_TARGETS ${lib} _IDX)
    list(APPEND _ALLLIBS ${lib}) # il faut ajouter la target elle même
    if (${_IDX} EQUAL -1)
      list(APPEND _DONE_TARGETS ${lib})
#      message(STATUS "ADD_DEPEND_LIB_TO_LIST LIB=${lib}")
      get_target_property(_LOC1 ${lib} INTERFACE_LINK_LIBRARIES)
      #message(STATUS "  LOCATION=${_LOC1}")
      list(APPEND _ALLLIBS ${_LOC1})
      #message(STATUS " DEPENDS = ${${lib}_DEPENDS}")
      foreach(sublib ${INTERFACE_LINK_LIBRARIES})
        arcane_vtkutils_add_depend_lib_to_list_v2(${sublib})
      endforeach()
    endif()
  endif()
endmacro()
