set(ARCANE_SOURCES
  CartesianMesh.cc
  CartesianConnectivity.cc
  CartesianConnectivity.h
  CellDirectionMng.cc
  CellDirectionMng.h
  FaceDirectionMng.cc
  FaceDirectionMng.h
  NodeDirectionMng.cc
  NodeDirectionMng.h
  CartesianConnectivity.h
  CartesianMeshRenumberingInfo.h
  CartesianItemDirectionInfo.h
  CellDirectionMng.h
  FaceDirectionMng.h
  NodeDirectionMng.h
  ICartesianMesh.h
  ICartesianMeshPatch.h
  CartesianPatch.h
  CartesianPatch.cc
  CartesianPatchGroup.h
  CartesianPatchGroup.cc
  CartesianMeshCoarsening.cc
  CartesianMeshCoarsening.h
  CartesianMeshCoarsening2.cc
  CartesianMeshCoarsening2.h
  CartesianMeshGlobal.h
  CartesianMeshUtils.h
  CartesianMeshUtils.cc
  CartesianMeshPatchListView.h
  internal/CartesianMeshPatch.h
  internal/CartesianMeshUniqueIdRenumbering.h
  internal/CartesianMeshUniqueIdRenumbering.cc
  internal/ICartesianMeshInternal.h
  CartesianMeshPatch.cc

  v2/CartesianGrid.h
  v2/CartesianNumbering.h
  v2/CartesianTypes.h
  v2/CartesianMeshUniqueIdRenumberingV2.h
  v2/CartesianMeshUniqueIdRenumberingV2.cc

  ICartesianMeshAMRPatchMng.h
  CartesianMeshAMRPatchMng.cc
  CartesianMeshAMRPatchMng.h

  ICartesianMeshNumberingMng.h
  CartesianMeshNumberingMng.cc
  CartesianMeshNumberingMng.h
  PatchAMRPosition.cc
  PatchAMRPosition.h
)
