#!/bin/bash

pkgsList=(\
"-DCMAKE_DISABLE_FIND_PACKAGE_HDF5=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_BZip2=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_LZ4=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_MEDFile=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_TBB=ON -DCMAKE_DISABLE_FIND_PACKAGE_vtkIOXdmf2=ON -DCMAKE_DISABLE_FIND_PACKAGE_vtkIOXML=ON -DCMAKE_DISABLE_FIND_PACKAGE_VTK=ON -DCMAKE_DISABLE_FIND_PACKAGE_ParaView=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_MKL=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_Otf2=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_OSMesa=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_IceT=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_CUDAToolkit=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_Hip=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_Parmetis=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_PTScotch=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_Zoltan=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_LibUnwind=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_Udunits=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_Valgrind=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_HWLoc=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_Hypre=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_SWIG=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_MonoEmbed=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_CoreClrEmbed=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_Mono=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_ParaView=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_VTK=ON -DCMAKE_DISABLE_FIND_PACKAGE_vtkIOXdmf2=ON -DCMAKE_DISABLE_FIND_PACKAGE_vtkIOXML=ON -DCMAKE_DISABLE_FIND_PACKAGE_ParaView=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_GeometryKernel=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_DbgHelp=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_AztecOO=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_ML=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_Ifpack=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_Belos=ON " \
"-DCMAKE_DISABLE_FIND_PACKAGE_Trilinos=ON " \
)
lenList=${#pkgsList[@]}
endList=""

for (( counter=0; counter<10; counter++ ))
do
  alea=$(( $RANDOM % $lenList ))
  elem=${pkgsList[$alea]}
  endList+=$elem
  pkgsList=("${pkgsList[@]/$elem}")
  lenList=$lenList-1
done
echo $endList