// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
#ifndef ARCGEOSIM_NUMERICS_LINEARSOLVER_ILINEARSYSTEMBUILDER_H
#define ARCGEOSIM_NUMERICS_LINEARSOLVER_ILINEARSYSTEMBUILDER_H
/* Author : desrozis at Mon Mar 30 15:52:09 2009
 * Generated by createNew
 */

/*! \brief Basic interface for builder
 *  Due to visitor techniques, all implementations are described below
 *  with a default implementation ("not implemented" error).
 *  When available, inherited class implements this interface (without error if not)
 */

// Définit s'il faut controler le profil lors du remplissage (accès couteux)
#define CHECKPROFILE_ON_DEBUG_FILLING

#include "Numerics/LinearSolver/ILinearSystemVisitor.h"

class ILinearSystem ;
class HypreLinearSystem ;
class PETScLinearSystem ;
class IFPLinearSystem ;
class LocalLinearSystem ;
class MTLLinearSystem ;

#include <arcane/utils/FatalErrorException.h>

#if not defined(NDEBUG) && defined(CHECKPROFILE_ON_DEBUG_FILLING)
#define CHECKPROFILE_ON_FILLING
#endif /* NDEBUG */

using namespace Arcane;

class ILinearSystemBuilder : public ILinearSystemVisitor
{
public:
  /** Constructeur de la classe */
  ILinearSystemBuilder() 
    {
      ;
    }
  
  /** Destructeur de la classe */
  virtual ~ILinearSystemBuilder() { }

  virtual void start() = 0 ;
  virtual void freeData() = 0 ;
  virtual void end() = 0 ;
  
  virtual bool connect       (ILinearSystem * system) { throw FatalErrorException(A_FUNCINFO,"not implemented"); }  
  virtual bool commitSolution(ILinearSystem * system) { throw FatalErrorException(A_FUNCINFO,"not implemented"); }

  virtual bool connect       (HypreLinearSystem* system) { throw FatalErrorException(A_FUNCINFO,"not implemented"); }  
  virtual bool commitSolution(HypreLinearSystem* system) { throw FatalErrorException(A_FUNCINFO,"not implemented"); }

  virtual bool connect       (PETScLinearSystem* system) { throw FatalErrorException(A_FUNCINFO,"not implemented"); }  
  virtual bool commitSolution(PETScLinearSystem* system) { throw FatalErrorException(A_FUNCINFO,"not implemented"); }

  virtual bool connect       (IFPLinearSystem* system) { throw FatalErrorException(A_FUNCINFO,"not implemented"); }  
  virtual bool commitSolution(IFPLinearSystem* system) { throw FatalErrorException(A_FUNCINFO,"not implemented"); }

  virtual bool connect       (LocalLinearSystem* system) { throw FatalErrorException(A_FUNCINFO,"not implemented"); }
  virtual bool commitSolution(LocalLinearSystem* system) { throw FatalErrorException(A_FUNCINFO,"not implemented"); }
  
  virtual bool connect       (MTLLinearSystem* system) { throw FatalErrorException(A_FUNCINFO,"not implemented"); }
  virtual bool commitSolution(MTLLinearSystem* system) { throw FatalErrorException(A_FUNCINFO,"not implemented"); }
};

#endif /* ARCGEOSIM_NUMERICS_LINEARSOLVER_ILINEARSYSTEMBUILDER_H */
