set(SOURCES
  AlinaGlobal.h
  AlinaGlobal.cc
  AlinaUtils.cc
  Adapters.h
  AlinaLib.h
  AlinaLib.cc
  AMG.h
  BlockCSRBackend.h
  BuiltinBackend.h
  HybridBuiltinBackend.h
  CudaBackend.h
  MatrixOperationsImpl.h
  BackendInterface.h
  BlockCSRMatrix.h
  CSRMatrix.h
  CSRMatrixOperations.h
  Coarsening.h
  CoarseningRuntime.h
  DeflatedSolver.h
  DenseMatrixInverseImpl.h
  ExecutionContext.h
  QRFactorizationImpl.h
  SparseMatrixMatrixProduct.h
  EigenAdapter.h
  EigenBackend.h
  IO.h
  ScopedStreamModifier.h
  make_block_solver.h
  PreconditionedSolver.h
  CPRDynamicRowSumPreconditioner.h
  CPRPreconditioner.h
  DummyPreconditioner.h
  PreconditionerRuntime.h
  SchurPressureCorrectionPreconditioner.h
  Profiler.h
  Profiler.cc
  relaxation_cusparse_ilu0.h
  ILUSolverImpl.h
  NumaVector.h
  RelaxationBase.h
  Relaxation.h
  RelaxationRuntime.h
  RelaxationRuntime.cc
  CuthillMcKeeReorderer.h
  BiCGStabSolver.h
  FlexibleGMRESSolver.h
  ConjugateGradientSolver.h
  EigenSolver.h
  FlexibleGMRESSolver.h
  GMRESSolver.h
  IDRSSolver.h
  LooseGMRESSolver.h
  SolverUtils.h
  PreconditionerOnlySolver.h
  RichardsonSolver.h
  SolverBase.h
  SolverRuntime.h
  SkylineLUSolver.h
  AlinaUtils.h
  ValueTypeInterface.h
  ValueTypeComplex.h
  ValueTypeEigen.h
  StaticMatrix.h

  DistributedAMG.h
  DistributedCoarsening.h
  DistributedCoarseningRuntime.h
  DistributedCPRPreconditioner.h
  DistributedDirectSolverBase.h
  DistributedDirectSolverRuntime.h
  DistributedEigenSparseLUDirectSolver.h
  DistributedSkylineLUDirectSolver.h
  DistributedMatrix.h
  DistributedInnerProduct.h
  DistributedPreconditioner.h
  DistributedPreconditionedSolver.h
  DistributedRelaxation.h
  DistributedRelaxationRuntime.h
  DistributedSchurPressureCorrection.h
  DistributedSolver.h
  DistributedSolverRuntime.h
  DistributedSubDomainDeflation.h
  SimpleMatrixPartitioner.h
  ParmetisMatrixPartitioner.h
  MatrixPartitionerRuntime.h
  MatrixPartitionUtils.h
  MessagePassingUtils.h
)
