if (NOT Axlstar_ROOT)
   # Pour compatibilité
   set(Axlstar_ROOT "${AXLSTAR_ROOT}")
endif()
if (NOT AXLSTAR_ROOT)
   message(FATAL_ERROR "Variable 'AXLSTAR_ROOT' is not set")
endif()
set(AXLSTAR_CMAKE_COMMANDS ${Axlstar_ROOT}/AxlstarUtilities.cmake)
set(AXLSTAR_CMAKE_COMMANDS ${Axlstar_ROOT}/AxlstarUtilities.cmake PARENT_SCOPE)
add_subdirectory(${Axlstar_ROOT} axlstar)
set(Axlstar_FOUND YES)
set(Axlstar_FOUND YES PARENT_SCOPE)
set(ARCANE_AXL2CC "${AXLSTAR_AXL2CC}")
set(ARCANE_AXL2CC "${AXLSTAR_AXL2CC}" PARENT_SCOPE)