set(SOURCES
  AllocatedMemoryInfo.h
  ArrayDebugInfo.h
  CommonGlobal.h
  CommonGlobal.cc
  IMemoryAllocator.h
  IMemoryResourceMng.h
  MemoryAllocator.cc
  MemoryAllocationArgs.h
  MemoryAllocationOptions.h
  MemoryAllocationOptions.cc
  MemoryUtils.cc
  internal/IMemoryResourceMngInternal.h
  internal/IMemoryCopier.h
  internal/SpecificMemoryCopyList.h
)
