set(SOURCES
  AbstractArray.h
  AllocatedMemoryInfo.h
  ArrayDebugInfo.h
  Array.h
  ArrayMetaData.h
  ArrayTraits.h
  Array.cc
  CommonGlobal.h
  CommonGlobal.cc
  IMemoryAllocator.h
  IMemoryResourceMng.h
  MemoryAllocator.cc
  MemoryAllocationArgs.h
  MemoryAllocationOptions.h
  MemoryAllocationOptions.cc
  MemoryUtils.cc
  SmallArray.h
  SmallArray.cc
  internal/IMemoryResourceMngInternal.h
  internal/IMemoryCopier.h
  internal/SpecificMemoryCopyList.h
)
