set( ARCANE_SOURCES
  Application.cc
  Application.h
  ArcaneCaseMeshMasterService.cc
  ArcaneCaseMeshService.cc
  ArcaneSimpleExecutor.h
  ArcaneSimpleExecutor.cc
  ArcaneSession.cc
  ArcaneSession.h
  ArcaneCodeService.cc
  ArcaneMain.cc
  ArcaneMain.h
  ArrayData.cc
  ArrayData.h
  ArcaneMainBatch.cc
  CaseDocument.cc
  CaseDocumentLangTranslator.cc
  CaseDocumentLangTranslator.h
  CaseMng.cc
  CheckpointMng.cc
  Configuration.cc
  ConfigurationReader.h
  ConfigurationReader.cc
  GetVariablesValuesParallelOperation.cc
  GetVariablesValuesParallelOperation.h
  Data.cc
  DataFactory.cc
  DataFactory.h
  DataFactoryMng.cc
  DataFactoryMng.h
  DataStorageFactory.h
  DataSynchronizeInfo.h
  DataSynchronizeInfo.cc
  DataSynchronizeBuffer.cc
  DataSynchronizeDispatcher.cc
  EntryPointMng.cc
  ExecutionStatsDumper.h
  ExecutionStatsDumper.cc
  FlexLMTools.h
  IOMng.cc
  InternalInfosDumper.h
  InternalInfosDumper.cc
  ItemEnumeratorTracer.cc
  ItemEnumeratorTracer.h
  MeshPartitionerTesterService.cc
  MainFactory.cc
  MainFactory.h
  ModuleMng.cc
  Array2Data.cc
  Array2Data.h
  MemoryDataReaderWriter.cc
  MemoryDataReaderWriter.h
  NumArrayData.cc
  DefaultBackwardMng.cc
  DefaultBackwardMng.h
  LoadBalanceMng.cc
  LoadBalanceMng.h
  NullVariableSynchronizer.cc
  ParallelExchanger.cc
  ParallelExchanger.h
  ParallelMngUtilsFactoryBase.cc
  ParallelMngUtilsFactoryBase.h
  ParallelReplication.cc
  ParallelReplication.h
  ParallelTopology.cc
  ParallelTopology.h
  PrintCaseDocumentVisitor.cc
  PropertyMng.cc
  SequentialParallelMng.cc
  SequentialParallelMng.h
  SerializedData.h
  StringScalarData.cc
  StringScalarData.h
  ScalarData.cc
  ScalarData.h
  ServiceLoader.cc
  ServiceMng.cc
  ServiceAndModuleFactoryMng.cc
  SimpleGridMeshPartitioner.cc
  Session.cc
  Session.h
  SubDomain.cc
  StringArrayData.cc
  StringArrayData.h
  TimeHistoryMng2.cc
  TimeLoopMng.cc
  TimeLoopReader.cc
  TimeLoopReader.h
  TimeStats.cc
  TimeStats.h
  TimerMng.cc
  TimerMng.h
  TransferValuesParallelOperation.cc
  TransferValuesParallelOperation.h
  VariableIOReaderMng.cc
  VariableIOWriterMng.cc
  VariableMng.cc
  VariableUtilities.cc
  VariableUtilities.h
  VariableSynchronizer.cc
  VariableSynchronizerMng.cc
  VariableSynchronizerComputeList.cc
  NullPhysicalUnitSystemService.cc
  TraceMngPolicy.cc
  GlibDynamicLibraryLoader.cc
  Application.h
  ArcaneSession.h
  ArcaneMain.h
  ArrayData.h
  CaseDocumentLangTranslator.h
  GetVariablesValuesParallelOperation.h
  DataFactory.h
  ItemEnumeratorTracer.h
  MainFactory.h
  Array2Data.h
  MemoryDataReaderWriter.h
  DefaultBackwardMng.h
  LoadBalanceMng.h
  ParallelExchanger.h
  ParallelReplication.h
  ParallelTopology.h
  SequentialParallelMng.h
  SerializedData.h
  StringScalarData.h
  ScalarData.h
  Session.h
  StringArrayData.h
  TimeLoopReader.h
  TimeStats.h
  TimerMng.h
  TransferValuesParallelOperation.h
  VariableUtilities.h
  IDataSynchronizeBuffer.h
  IDataSynchronizeImplementation.h
  DataOperation.h
  DataOperation.cc
  SequentialParallelSuperMng.h

  internal/ArcaneMainExecInfo.h
  internal/DataSynchronizeBuffer.h
  internal/IDataSynchronizeDispatcher.h
  internal/LegacyMeshBuilder.h
  internal/LegacyMeshBuilder.cc
  internal/MeshFactoryMng.h
  internal/MeshFactoryMng.cc
  internal/MeshMng.h
  internal/MeshMng.cc
  internal/ThreadBindingMng.h
  internal/ThreadBindingMng.cc
  internal/VariableMng.h
  internal/VariableSynchronizer.h
  internal/VariableSynchronizerMng.h
  internal/VariableSynchronizerComputeList.h
  )

set(AXL_FILES
  ArcaneCaseMeshMasterService
  ArcaneCaseMeshService
  MeshPartitionerTesterService
)
