set(ARCANE_SOURCES
  CheckpointTesterService.cc
  JSONUnitTest.cc
  XmlUnitTest.cc
  SingletonService.cc
  ParticleUnitTest.cc
  TestUnitTest.cc
  CaseOptionsTesterModule.cc
  ParallelTesterModule.cc
  SubMeshTestModule.cc
  TestTplParameter.cc
  ModuleSimpleHydro.cc
  ModuleSimpleHydroGeneric.cc
  ModuleSimpleHydroSimd.cc
  ModuleSimpleHydroDepend.cc
  MeshMergeNodesUnitTest.cc
  MeshUnitTest.cc
  MultipleMeshUnitTest.cc
  ThreadUnitTest.cc
  TaskUnitTestCS.cc
  IosUnitTest.cc
  VariableUnitTest.cc
  VariableSimdUnitTest.cc
  AMRTestModule.cc
  MatVecUnitTest.cc
  MiniWeatherTypes.h
  MiniWeatherModule.cc
  StdArrayMeshVariables.cc
  StdArrayMeshVariables.h
  StdMeshVariables.cc
  StdMeshVariables.h
  StdScalarVariables.cc
  StdScalarVariables.h
  StdScalarMeshVariables.cc
  StdScalarMeshVariables.h
  PartialVariableTester.cc
  RandomUnitTest.cc
  ArrayUnitTest.cc
  PropertiesUnitTest.cc
  ItemVectorUnitTest.cc
  ConfigurationUnitTest.cc
  VoronoiTest.cc
  UtilsUnitTest.cc
  SimdUnitTest.cc
  ParallelMngTest.cc
  ParallelMngDataTypeTest.cc
  SingletonServiceTestModule.cc
  TimeHistoryTestModule.cc
  MeshModificationTester.cc
  DirectedGraphUnitTest.cc
  ExchangeItemsUnitTest.cc
  anyitem/AnyItemTester.cc
  dof/DoFTester.cc
  graph/GraphUnitTest.cc
  inout/InOutTester.cc
  geometry/GeometryUnitTest.cc
  StdArrayMeshVariables.h
  StdMeshVariables.h
  StdScalarVariables.h
  StdScalarMeshVariables.h
  IServiceInterface.h
  ArcaneTestInit.cc
  ArcaneTestDirectExecution.cc
  accelerator/MiniWeatherOriginalSequential.cc
  accelerator/MiniWeatherArraySequential.cc
  CustomMeshTestModule.cc
  TaskUnitTest.cc
  PDESRandomNumberGeneratorUnitTest.cc
  RandomNumberGeneratorUnitTest.cc
  SimpleTableOutputUnitTest.cc
)

set(AXL_FILES
  CheckpointTester
  SimpleHydro
  ScriptTester
  CaseOptionsTester
  ParallelTester
  SubMeshTest
  SingletonService
  ParticleUnitTest
  TestUnitTest
  MeshMergeNodesUnitTest
  MeshUnitTest
  ThreadUnitTest
  TaskUnitTest
  IosUnitTest
  VariableUnitTest
  AMRTest
  MatVecUnitTest
  MiniWeather
  PartialVariableTester
  VoronoiTest
  SingletonServiceTest
  TimeHistoryTest
  MeshModificationTester
  DirectedGraphUnitTest
  ExchangeItemsUnitTest
  anyitem/AnyItemTester
  dof/DoFTester
  graph/GraphUnitTest
  inout/InOutTester
  geometry/GeometryUnitTest
  CustomMeshTest
  accelerator/SimpleHydroAccelerator
  PDESRandomNumberGeneratorUnitTest
  RandomNumberGeneratorUnitTest
  SimpleTableOutputUnitTest
)

