//!-- -*- C++ -*- --
#include "arcane/IMesh.h"
#include "arcane/IItemFamily.h"
#include "arcane/Item.h"
#include "arcane/IItemOperationByBasicType.h"
#include "arcane/ItemGroup.h"
#include "arcane/MeshUtils.h"
#include "arcane/TiedNode.h"
#include "arcane/TiedFace.h"
#include "arcane/ITiedInterface.h"
#include "arcane/ItemTypeMng.h"
