//!-- -*- C++ -*- --
#include "arcane/core/IMesh.h"
#include "arcane/core/IItemFamily.h"
#include "arcane/core/Item.h"
#include "arcane/core/IItemOperationByBasicType.h"
#include "arcane/core/ItemGroup.h"
#include "arcane/core/MeshUtils.h"
#include "arcane/core/TiedNode.h"
#include "arcane/core/TiedFace.h"
#include "arcane/core/ITiedInterface.h"
#include "arcane/core/ItemTypeMng.h"
