set( ARCANE_SOURCES
  CartesianMesh.cc
  CartesianConnectivity.cc
  CartesianConnectivity.h
  CellDirectionMng.cc
  CellDirectionMng.h
  FaceDirectionMng.cc
  FaceDirectionMng.h
  NodeDirectionMng.cc
  NodeDirectionMng.h
  CartesianConnectivity.h
  CartesianMeshRenumberingInfo.h
  CellDirectionMng.h
  FaceDirectionMng.h
  NodeDirectionMng.h
  ICartesianMesh.h
  ICartesianMeshPatch.h
  CartesianMeshGlobal.h
  internal/CartesianMeshPatch.h
  internal/CartesianMeshUniqueIdRenumbering.h
  internal/CartesianMeshUniqueIdRenumbering.cc
  CartesianMeshPatch.cc
  )
