// WARNING: This file is generated by a tool. DO NOT EDIT.
/*
 * Generation of view classes for geometric elements (GeomElement).
 */

/*!
 * \ingroup ArcaneGeometric
 * \brief Constant view on geometric elements of type GeomType::Triangle3.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from an instance of Triangle3ShapeView.
 * - directly from an instance of Triangle3Element
 * - an instance of Triangle3ElementView via Triangle3ElementView::constView()
 * - an instance of GeomShapeView via GeomShapeView::toTriangle3Element()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Triangle3ElementConstView
: public GeomElementConstViewBase
{
 public:
  Triangle3ElementConstView(ARCANE_RESTRICT const Real3POD* ptr)
  : GeomElementConstViewBase(ptr){}
};

/*!
 * \ingroup ArcaneGeometric
 * \brief Modifiable view on geometric elements of type GeomType::Triangle3.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from an instance of Triangle3Element
 * - an instance of Triangle3Element via Triangle3ElementView::view()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Triangle3ElementView
: public GeomElementViewBase
{
 public:
  typedef Triangle3ElementConstView ConstViewType;
 public:
  Triangle3ElementView(ARCANE_RESTRICT Real3POD* ptr)
  : GeomElementViewBase(ptr){}
  //! Initializes the view with the coordinates passed as arguments
  void init(const Real3& a0, const Real3& a1, const Real3& a2)
  {
      m_s[0] = a0;
      m_s[1] = a1;
      m_s[2] = a2;
     }
  //! Conversion operator to a constant view
  operator Triangle3ElementConstView() const { return ConstViewType(m_s); }
  //! Constant view on the element
  Triangle3ElementConstView constView() const { return ConstViewType(m_s); }
};

//! View on an element of type GeomType::Triangle3
typedef Triangle3ElementView TriangleElementView;
//! Constant view on an element of type GeomType::Triangle3
typedef Triangle3ElementConstView TriangleElementConstView;


/*!
 * \ingroup ArcaneGeometric
 * \brief Constant view on geometric elements of type GeomType::Quad4.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from an instance of Quad4ShapeView.
 * - directly from an instance of Quad4Element
 * - an instance of Quad4ElementView via Quad4ElementView::constView()
 * - an instance of GeomShapeView via GeomShapeView::toQuad4Element()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Quad4ElementConstView
: public GeomElementConstViewBase
{
 public:
  Quad4ElementConstView(ARCANE_RESTRICT const Real3POD* ptr)
  : GeomElementConstViewBase(ptr){}
};

/*!
 * \ingroup ArcaneGeometric
 * \brief Modifiable view on geometric elements of type GeomType::Quad4.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from an instance of Quad4Element
 * - an instance of Quad4Element via Quad4ElementView::view()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Quad4ElementView
: public GeomElementViewBase
{
 public:
  typedef Quad4ElementConstView ConstViewType;
 public:
  Quad4ElementView(ARCANE_RESTRICT Real3POD* ptr)
  : GeomElementViewBase(ptr){}
  //! Initializes the view with the coordinates passed as arguments
  void init(const Real3& a0, const Real3& a1, const Real3& a2, const Real3& a3)
  {
      m_s[0] = a0;
      m_s[1] = a1;
      m_s[2] = a2;
      m_s[3] = a3;
     }
  //! Conversion operator to a constant view
  operator Quad4ElementConstView() const { return ConstViewType(m_s); }
  //! Constant view on the element
  Quad4ElementConstView constView() const { return ConstViewType(m_s); }
};

//! View on an element of type GeomType::Quad4
typedef Quad4ElementView QuadElementView;
//! Constant view on an element of type GeomType::Quad4
typedef Quad4ElementConstView QuadElementConstView;


/*!
 * \ingroup ArcaneGeometric
 * \brief Constant view on geometric elements of type GeomType::Pentagon5.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from an instance of Pentagon5ShapeView.
 * - directly from an instance of Pentagon5Element
 * - an instance of Pentagon5ElementView via Pentagon5ElementView::constView()
 * - an instance of GeomShapeView via GeomShapeView::toPentagon5Element()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Pentagon5ElementConstView
: public GeomElementConstViewBase
{
 public:
  Pentagon5ElementConstView(ARCANE_RESTRICT const Real3POD* ptr)
  : GeomElementConstViewBase(ptr){}
};

/*!
 * \ingroup ArcaneGeometric
 * \brief Modifiable view on geometric elements of type GeomType::Pentagon5.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from an instance of Pentagon5Element
 * - an instance of Pentagon5Element via Pentagon5ElementView::view()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Pentagon5ElementView
: public GeomElementViewBase
{
 public:
  typedef Pentagon5ElementConstView ConstViewType;
 public:
  Pentagon5ElementView(ARCANE_RESTRICT Real3POD* ptr)
  : GeomElementViewBase(ptr){}
  //! Initializes the view with the coordinates passed as arguments
  void init(const Real3& a0, const Real3& a1, const Real3& a2, const Real3& a3, const Real3& a4)
  {
      m_s[0] = a0;
      m_s[1] = a1;
      m_s[2] = a2;
      m_s[3] = a3;
      m_s[4] = a4;
     }
  //! Conversion operator to a constant view
  operator Pentagon5ElementConstView() const { return ConstViewType(m_s); }
  //! Constant view on the element
  Pentagon5ElementConstView constView() const { return ConstViewType(m_s); }
};

//! View on an element of type GeomType::Pentagon5
typedef Pentagon5ElementView PentagonElementView;
//! Constant view on an element of type GeomType::Pentagon5
typedef Pentagon5ElementConstView PentagonElementConstView;


/*!
 * \ingroup ArcaneGeometric
 * \brief Constant view on geometric elements of type GeomType::Hexagon6.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from an instance of Hexagon6ShapeView.
 * - directly from an instance of Hexagon6Element
 * - an instance of Hexagon6ElementView via Hexagon6ElementView::constView()
 * - an instance of GeomShapeView via GeomShapeView::toHexagon6Element()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Hexagon6ElementConstView
: public GeomElementConstViewBase
{
 public:
  Hexagon6ElementConstView(ARCANE_RESTRICT const Real3POD* ptr)
  : GeomElementConstViewBase(ptr){}
};

/*!
 * \ingroup ArcaneGeometric
 * \brief Modifiable view on geometric elements of type GeomType::Hexagon6.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from an instance of Hexagon6Element
 * - an instance of Hexagon6Element via Hexagon6ElementView::view()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Hexagon6ElementView
: public GeomElementViewBase
{
 public:
  typedef Hexagon6ElementConstView ConstViewType;
 public:
  Hexagon6ElementView(ARCANE_RESTRICT Real3POD* ptr)
  : GeomElementViewBase(ptr){}
  //! Initializes the view with the coordinates passed as arguments
  void init(const Real3& a0, const Real3& a1, const Real3& a2, const Real3& a3, const Real3& a4, const Real3& a5)
  {
      m_s[0] = a0;
      m_s[1] = a1;
      m_s[2] = a2;
      m_s[3] = a3;
      m_s[4] = a4;
      m_s[5] = a5;
     }
  //! Conversion operator to a constant view
  operator Hexagon6ElementConstView() const { return ConstViewType(m_s); }
  //! Constant view on the element
  Hexagon6ElementConstView constView() const { return ConstViewType(m_s); }
};

//! View on an element of type GeomType::Hexagon6
typedef Hexagon6ElementView HexagonElementView;
//! Constant view on an element of type GeomType::Hexagon6
typedef Hexagon6ElementConstView HexagonElementConstView;


/*!
 * \ingroup ArcaneGeometric
 * \brief Constant view on geometric elements of type GeomType::Tetraedron4.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from an instance of Tetraedron4ShapeView.
 * - directly from an instance of Tetraedron4Element
 * - an instance of Tetraedron4ElementView via Tetraedron4ElementView::constView()
 * - an instance of GeomShapeView via GeomShapeView::toTetraedron4Element()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Tetraedron4ElementConstView
: public GeomElementConstViewBase
{
 public:
  Tetraedron4ElementConstView(ARCANE_RESTRICT const Real3POD* ptr)
  : GeomElementConstViewBase(ptr){}
};

/*!
 * \ingroup ArcaneGeometric
 * \brief Modifiable view on geometric elements of type GeomType::Tetraedron4.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from an instance of Tetraedron4Element
 * - an instance of Tetraedron4Element via Tetraedron4ElementView::view()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Tetraedron4ElementView
: public GeomElementViewBase
{
 public:
  typedef Tetraedron4ElementConstView ConstViewType;
 public:
  Tetraedron4ElementView(ARCANE_RESTRICT Real3POD* ptr)
  : GeomElementViewBase(ptr){}
  //! Initializes the view with the coordinates passed as arguments
  void init(const Real3& a0, const Real3& a1, const Real3& a2, const Real3& a3)
  {
      m_s[0] = a0;
      m_s[1] = a1;
      m_s[2] = a2;
      m_s[3] = a3;
     }
  //! Conversion operator to a constant view
  operator Tetraedron4ElementConstView() const { return ConstViewType(m_s); }
  //! Constant view on the element
  Tetraedron4ElementConstView constView() const { return ConstViewType(m_s); }
};

//! View on an element of type GeomType::Tetraedron4
typedef Tetraedron4ElementView TetraElementView;
//! Constant view on an element of type GeomType::Tetraedron4
typedef Tetraedron4ElementConstView TetraElementConstView;


/*!
 * \ingroup ArcaneGeometric
 * \brief Constant view on geometric elements of type GeomType::Pyramid5.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from an instance of Pyramid5ShapeView.
 * - directly from a Pyramid5Element instance
 * - a Pyramid5ElementView instance via Pyramid5ElementView::constView()
 * - a GeomShapeView instance via GeomShapeView::toPyramid5Element()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Pyramid5ElementConstView
: public GeomElementConstViewBase
{
 public:
  Pyramid5ElementConstView(ARCANE_RESTRICT const Real3POD* ptr)
  : GeomElementConstViewBase(ptr){}
};

/*!
 * \ingroup ArcaneGeometric
 * \brief Modifiable view on geometric elements of type GeomType::Pyramid5.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from a Pyramid5Element instance
 * - a Pyramid5Element instance via Pyramid5ElementView::view()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Pyramid5ElementView
: public GeomElementViewBase
{
 public:
  typedef Pyramid5ElementConstView ConstViewType;
 public:
  Pyramid5ElementView(ARCANE_RESTRICT Real3POD* ptr)
  : GeomElementViewBase(ptr){}
  //! Initializes the view with the coordinates passed as arguments
  void init(const Real3& a0, const Real3& a1, const Real3& a2, const Real3& a3, const Real3& a4)
  {
      m_s[0] = a0;
      m_s[1] = a1;
      m_s[2] = a2;
      m_s[3] = a3;
      m_s[4] = a4;
     }
  //! Conversion operator to a constant view
  operator Pyramid5ElementConstView() const { return ConstViewType(m_s); }
  //! Constant view on the element
  Pyramid5ElementConstView constView() const { return ConstViewType(m_s); }
};

//! View on a GeomType::Pyramid5 element
typedef Pyramid5ElementView PyramidElementView;
//! Constant view on a GeomType::Pyramid5 element
typedef Pyramid5ElementConstView PyramidElementConstView;


/*!
 * \ingroup ArcaneGeometric
 * \brief Constant view on geometric elements of type GeomType::Pentaedron6.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from a Pentaedron6ShapeView instance.
 * - directly from a Pentaedron6Element instance
 * - a Pentaedron6ElementView instance via Pentaedron6ElementView::constView()
 * - a GeomShapeView instance via GeomShapeView::toPentaedron6Element()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Pentaedron6ElementConstView
: public GeomElementConstViewBase
{
 public:
  Pentaedron6ElementConstView(ARCANE_RESTRICT const Real3POD* ptr)
  : GeomElementConstViewBase(ptr){}
};

/*!
 * \ingroup ArcaneGeometric
 * \brief Modifiable view on geometric elements of type GeomType::Pentaedron6.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from a Pentaedron6Element instance
 * - a Pentaedron6Element instance via Pentaedron6ElementView::view()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Pentaedron6ElementView
: public GeomElementViewBase
{
 public:
  typedef Pentaedron6ElementConstView ConstViewType;
 public:
  Pentaedron6ElementView(ARCANE_RESTRICT Real3POD* ptr)
  : GeomElementViewBase(ptr){}
  //! Initializes the view with the coordinates passed as arguments
  void init(const Real3& a0, const Real3& a1, const Real3& a2, const Real3& a3, const Real3& a4, const Real3& a5)
  {
      m_s[0] = a0;
      m_s[1] = a1;
      m_s[2] = a2;
      m_s[3] = a3;
      m_s[4] = a4;
      m_s[5] = a5;
     }
  //! Conversion operator to a constant view
  operator Pentaedron6ElementConstView() const { return ConstViewType(m_s); }
  //! Constant view on the element
  Pentaedron6ElementConstView constView() const { return ConstViewType(m_s); }
};

//! View on a GeomType::Pentaedron6 element
typedef Pentaedron6ElementView PentaElementView;
//! Constant view on a GeomType::Pentaedron6 element
typedef Pentaedron6ElementConstView PentaElementConstView;


/*!
 * \ingroup ArcaneGeometric
 * \brief Constant view on geometric elements of type GeomType::Hexaedron8.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from a Hexaedron8ShapeView instance.
 * - directly from a Hexaedron8Element instance
 * - a Hexaedron8ElementView instance via Hexaedron8ElementView::constView()
 * - a GeomShapeView instance via GeomShapeView::toHexaedron8Element()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Hexaedron8ElementConstView
: public GeomElementConstViewBase
{
 public:
  Hexaedron8ElementConstView(ARCANE_RESTRICT const Real3POD* ptr)
  : GeomElementConstViewBase(ptr){}
};

/*!
 * \ingroup ArcaneGeometric
 * \brief Modifiable view on geometric elements of type GeomType::Hexaedron8.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from a Hexaedron8Element instance
 * - a Hexaedron8Element instance via Hexaedron8ElementView::view()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Hexaedron8ElementView
: public GeomElementViewBase
{
 public:
  typedef Hexaedron8ElementConstView ConstViewType;
 public:
  Hexaedron8ElementView(ARCANE_RESTRICT Real3POD* ptr)
  : GeomElementViewBase(ptr){}
  //! Initializes the view with the coordinates passed as arguments
  void init(const Real3& a0, const Real3& a1, const Real3& a2, const Real3& a3, const Real3& a4, const Real3& a5, const Real3& a6, const Real3& a7)
  {
      m_s[0] = a0;
      m_s[1] = a1;
      m_s[2] = a2;
      m_s[3] = a3;
      m_s[4] = a4;
      m_s[5] = a5;
      m_s[6] = a6;
      m_s[7] = a7;
     }
  //! Conversion operator to a constant view
  operator Hexaedron8ElementConstView() const { return ConstViewType(m_s); }
  //! Constant view on the element
  Hexaedron8ElementConstView constView() const { return ConstViewType(m_s); }
};

//! View on a GeomType::Hexaedron8 element
typedef Hexaedron8ElementView HexaElementView;
//! Constant view on a GeomType::Hexaedron8 element
typedef Hexaedron8ElementConstView HexaElementConstView;


/*!
 * \ingroup ArcaneGeometric
 * \brief Constant view on geometric elements of type GeomType::Heptaedron10.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from a Heptaedron10ShapeView instance.
 * - directly from a Heptaedron10Element instance
 * - a Heptaedron10ElementView instance via Heptaedron10ElementView::constView()
 * - a GeomShapeView instance via GeomShapeView::toHeptaedron10Element()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Heptaedron10ElementConstView
: public GeomElementConstViewBase
{
 public:
  Heptaedron10ElementConstView(ARCANE_RESTRICT const Real3POD* ptr)
  : GeomElementConstViewBase(ptr){}
};

/*!
 * \ingroup ArcaneGeometric
 * \brief Modifiable view on geometric elements of type GeomType::Heptaedron10.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from a Heptaedron10Element instance
 * - a Heptaedron10Element instance via Heptaedron10ElementView::view()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Heptaedron10ElementView
: public GeomElementViewBase
{
 public:
  typedef Heptaedron10ElementConstView ConstViewType;
 public:
  Heptaedron10ElementView(ARCANE_RESTRICT Real3POD* ptr)
  : GeomElementViewBase(ptr){}
  //! Initializes the view with the coordinates passed as arguments
  void init(const Real3& a0, const Real3& a1, const Real3& a2, const Real3& a3, const Real3& a4, const Real3& a5, const Real3& a6, const Real3& a7, const Real3& a8, const Real3& a9)
  {
      m_s[0] = a0;
      m_s[1] = a1;
      m_s[2] = a2;
      m_s[3] = a3;
      m_s[4] = a4;
      m_s[5] = a5;
      m_s[6] = a6;
      m_s[7] = a7;
      m_s[8] = a8;
      m_s[9] = a9;
     }
  //! Conversion operator to a constant view
  operator Heptaedron10ElementConstView() const { return ConstViewType(m_s); }
  //! Constant view on the element
  Heptaedron10ElementConstView constView() const { return ConstViewType(m_s); }
};

//! View on a GeomType::Heptaedron10 element
typedef Heptaedron10ElementView Wedge7ElementView;
//! Constant view on a GeomType::Heptaedron10 element
typedef Heptaedron10ElementConstView Wedge7ElementConstView;


/*!
 * \ingroup ArcaneGeometric
 * \brief Constant view on geometric elements of type GeomType::Octaedron12.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from an Octaedron12ShapeView instance.
 * - directly from an Octaedron12Element instance
 * - an Octaedron12ElementView instance via Octaedron12ElementView::constView()
 * - a GeomShapeView instance via GeomShapeView::toOctaedron12Element()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Octaedron12ElementConstView
: public GeomElementConstViewBase
{
 public:
  Octaedron12ElementConstView(ARCANE_RESTRICT const Real3POD* ptr)
  : GeomElementConstViewBase(ptr){}
};

/*!
 * \ingroup ArcaneGeometric
 * \brief Modifiable view on geometric elements of type GeomType::Octaedron12.
 * 
 * It is possible to retrieve a view of this type via:
 * - directly from an Octaedron12Element instance
 * - an Octaedron12Element instance via Octaedron12ElementView::view()
 *
 * For more information on usage, refer to \ref arcanedoc_cea_geometric_viewusage
 */
class ARCANE_GEOMETRY_EXPORT Octaedron12ElementView
: public GeomElementViewBase
{
 public:
  typedef Octaedron12ElementConstView ConstViewType;
 public:
  Octaedron12ElementView(ARCANE_RESTRICT Real3POD* ptr)
  : GeomElementViewBase(ptr){}
  //! Initializes the view with the coordinates passed as arguments
  void init(const Real3& a0, const Real3& a1, const Real3& a2, const Real3& a3, const Real3& a4, const Real3& a5, const Real3& a6, const Real3& a7, const Real3& a8, const Real3& a9, const Real3& a10, const Real3& a11)
  {
      m_s[0] = a0;
      m_s[1] = a1;
      m_s[2] = a2;
      m_s[3] = a3;
      m_s[4] = a4;
      m_s[5] = a5;
      m_s[6] = a6;
      m_s[7] = a7;
      m_s[8] = a8;
      m_s[9] = a9;
      m_s[10] = a10;
      m_s[11] = a11;
     }
  //! Conversion operator to a constant view
  operator Octaedron12ElementConstView() const { return ConstViewType(m_s); }
  //! Constant view on the element
  Octaedron12ElementConstView constView() const { return ConstViewType(m_s); }
};

//! View on a GeomType::Octaedron12 element
typedef Octaedron12ElementView Wedge8ElementView;
//! Constant view on a GeomType::Octaedron12 element
typedef Octaedron12ElementConstView Wedge8ElementConstView;
