#ifndef ALIEN_KERNELS_PETSC_FIELDSPLIT_IFIELDSPLITTYPE_H
#define ALIEN_KERNELS_PETSC_FIELDSPLIT_IFIELDSPLITTYPE_H
/* Author : havep at Tue Aug 21 10:42:14 2012
 * Generated by createNew
 */

// Pas de pré-déclaration possible sans utiliser les types internes PETSc (_p_PC)
#include "petscpc.h"
#include <alien/kernels/petsc/PETScPrecomp.h>

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/
namespace Alien {
class IFieldSplitType
{
 public:
  /** Destructeur de la classe */
  virtual ~IFieldSplitType() {}

 public:
  //! Configure FieldSplit type
  /*! Returns an int as a PETSc error code */
  virtual Arccore::Integer configure(PC& pc, const Arccore::Integer nbField) = 0;
};
} // namespace Alien
/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif /* ALIEN_KERNELS_PETSC_FIELDSPLIT_IFIELDSPLITTYPE_H */
