set(SOURCES
  ConcurrencyGlobal.h
  ConcurrencyGlobal.cc
  IThreadImplementation.h
  IThreadBarrier.h
  Mutex.h
  Mutex.cc
  NullThreadImplementation.h
  SpinLock.h
  SpinLock.cc
  StdThreadImplementation.cc
)
