set(SOURCES
  ConcurrencyGlobal.h
  ConcurrencyGlobal.cc
  ConcurrencyUtils.cc
  ITaskImplementation.h
  IThreadImplementation.h
  IThreadBarrier.h
  ParallelFor.h
  Mutex.h
  Mutex.cc
  NullThreadImplementation.h
  SpinLock.h
  SpinLock.cc
  StdThreadImplementation.cc
  Task.h
  TaskFactory.h
  internal/TaskFactoryInternal.h
)
