set( ARCANE_SOURCES
  Accelerator.cc
  Accelerator.h
  AcceleratorGlobal.h
  Reduce.h
  Runner.h
  Runner.cc
  RunCommand.h
  RunCommand.cc
  IReduceMemoryImpl.h
  IRunQueueRuntime.h
  RunQueueRuntime.cc
  RunQueueInternal.h
  RunQueueInternal.cc
  RunQueueImpl.h
  RunQueueImpl.cc
  RunQueue.h
  RunQueue.cc
  Views.h
  ViewsCommon.h
  NumArray.h
  NumArray.cc
  NumArrayViews.h
)
