set(GLPK_NAME "glpk")

set(GLPK_ROOT_DIR $ENV{EBROOTGLPK})

find_path(GLPK_INCLUDE_DIR glpk.h
  PATHS ${GLPK_ROOT_DIR}/include NO_DEFAULT_PATH)
  
find_library(GLPK_LIBRARY glpk
  PATHS ${GLPK_ROOT_DIR}/lib NO_DEFAULT_PATH)
  
set(GLPK_FOUND "NO")
if(GLPK_INCLUDE_DIR)
  if(NOT GLPK_LIBRARY_FAILED)
    set(GLPK_FOUND "YES" CACHE STRING "GLPK found" FORCE)
    set(GLPK_INCLUDE_DIRS ${GLPK_INCLUDE_DIR})
    set(GLPK_LIBRARIES ${GLPK_LIBRARY})
    add_library(glpk UNKNOWN IMPORTED)
    set_target_properties(glpk PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${GLPK_INCLUDE_DIRS}")
    set_target_properties(glpk PROPERTIES IMPORTED_LINK_INTERFACE_LANGUAGES "CXX" IMPORTED_LOCATION "${GLPK_LIBRARIES}")
    add_definitions(-DUSE_GLPK)
  endif(NOT GLPK_LIBRARY_FAILED)
endif(GLPK_INCLUDE_DIR)

list(APPEND REQUIRED_DEPENDENCIES GLPK)
