// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2022 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
#ifndef ARCANEDEMO_PARALLELCOREFINEMENT_IPARALLELCOREFINEMENT_H
#define ARCANEDEMO_PARALLELCOREFINEMENT_IPARALLELCOREFINEMENT_H
/* Author : havep at Wed Feb 18 14:18:13 2009
 * Generated by createNew
 */

#include <arcane/utils/Real3.h>
#include <arcane/Item.h>

#include <arcane/corefinement/surfaceutils/ISurfaceUtils.h>

ARCANE_BEGIN_NAMESPACE
NUMERICS_BEGIN_NAMESPACE

using namespace Arcane;

//! Pré-déclaration
class IGeometry;

//! Interface du co-raffinement parallèle
class IParallelCorefinement
{
public:
  typedef ISurfaceUtils::FaceFaceContactList FaceFaceContactList;

public:
  /** Constructeur de la classe */
  IParallelCorefinement() 
    {
      ;
    }
  
  /** Destructeur de la classe */
  virtual ~IParallelCorefinement() { }
  
public:
  //! Initialisation
  virtual void init(const FaceGroup & masterGroup, 
                    const FaceGroup & slaveGroup, 
                    const Real boxTolerance,
                    IGeometry * geometry) = 0;

  //! Update
  virtual void update() = 0;

  //! Access to computed contacts
  virtual const ISurfaceUtils::FaceFaceContactList & contacts() = 0;
};

NUMERICS_END_NAMESPACE
ARCANE_END_NAMESPACE

#endif /* ARCANEDEMO_PARALLELCOREFINEMENT_IPARALLELCOREFINEMENT_H */
