// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2026 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
#ifndef ARCGEOSIM_GEOMETRY_GEOMETRYSERVICEBASE_H
#define ARCGEOSIM_GEOMETRY_GEOMETRYSERVICEBASE_H
/* Author : havep at Thu Apr  3 09:09:09 2008
 * Generated by createNew
 */

#include "arcane/geometry/IGeometryMng.h"
#include "arcane/geometry/impl/ItemGroupGeometryProperty.h"

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

namespace Arcane
{
class ISubDomain;
}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

namespace Arcane::Numerics
{

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

class GeometryServiceBase
: public IGeometryMng
{
 public:

  /** Class constructor */
  GeometryServiceBase();

  /** Class destructor */
  virtual ~GeometryServiceBase();

 public:

  //@{ @name Geometric property management for ItemGroup

  //! Set geometric properties on an ItemGroup
  void addItemGroupProperty(ItemGroup group, Integer property, Integer storage = IGeometryProperty::PVariable);

  //! Set geometric properties on an ItemGroup with an external container (real field)
  void addItemGroupProperty(ItemGroup group, IGeometryProperty::eProperty property, RealVariable var);

  //! Set geometric properties on an ItemGroup with an external container (real3 field)
  void addItemGroupProperty(ItemGroup group, IGeometryProperty::eProperty property, Real3Variable var);

  //! Get set of properties of an ItemGroup
  Integer getItemGroupProperty(ItemGroup group);

  //! Check if a property is activated on an ItemGroup
  bool hasItemGroupProperty(ItemGroup group, Integer property);

  //! Check if storage is available on an ItemGroup
  Integer getItemGroupPropertyStorage(ItemGroup group, IGeometryProperty::eProperty property);

  //@}

  //@{ @name Access to geometric values
  //! Get geometric property values for a Real field
  const RealVariable& getRealVariableProperty(ItemGroup group, IGeometryProperty::eProperty property);

  //! Get geometric property values for a Real3 field
  const Real3Variable& getReal3VariableProperty(ItemGroup group, IGeometryProperty::eProperty property);
  //@}

  //@{ @name property management by group and properties

  //! Update property values for an ItemGroup
  void update(ItemGroup group, Integer property);

  //! Reset property for an ItemGroup
  void reset(ItemGroup group, Integer property);

  //@}

  //@{ @name property management by group

  //! Update property values for an ItemGroup
  virtual void update(ItemGroup group) = 0;

  //! Reset property for an ItemGroup
  virtual void reset(ItemGroup group) = 0;

  //@}

  //@{ @name global property management

  //! Update property values for all ItemGroups
  void update();

  //! Reset property for all ItemGroups
  void reset();

  //@}

 protected:

  //@{ Local extension of the interface

  //! Access to traceMng
  virtual ITraceMng* traceMng() = 0;

  //! Access to mesh
  virtual IMesh* mesh() = 0;

  template <typename GeometryT>
  void updateGroup(ItemGroup group, GeometryT& geometry);

  //! Name of instantiated class
  virtual const char* className() const = 0;

  //@}

 protected:

  typedef std::map<ItemGroupImpl*, ItemGroupGeometryProperty> PropertyMap;
  PropertyMap m_group_property_map;
  String m_suffix; //!< suffix for internal variable names

  //! Return ItemGroupGeometryProperty if requested property and storage are available
  ItemGroupGeometryProperty::StorageInfo& _checkItemGroupProperty(ItemGroupImpl* group,
                                                                  IGeometryProperty::eProperty property,
                                                                  IGeometryProperty::eStorage storage);
  void _resetComputeFlags();
  void _checkItemGroupUsage();
  /*! Using setSuffix allows defining a known extension for internal variable names.
   *  At this level, the user is responsible for name collision management */
  void setSuffix(const String& suffix) { m_suffix = suffix; }
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

} // namespace Arcane::Numerics

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#include "GeometryServiceBaseT.h"

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif
