set( ARCANE_SOURCES
  ArcaneMpi.cc
  ArcaneMpi.h
  IVariableSynchronizerMpiCommunicator.h
  MpiParallelSuperMng.cc
  MpiDatatypeList.cc
  MpiDatatypeList.h
  MpiErrorHandler.h
  MpiErrorHandler.cc
  MpiParallelMng.cc
  MpiParallelMng.h
  MpiParallelDispatch.cc
  MpiParallelDispatch.h
  MpiParallelNonBlockingCollective.cc
  MpiParallelNonBlockingCollective.h
  MpiParallelNonBlockingCollectiveDispatch.cc
  MpiParallelNonBlockingCollectiveDispatch.h
  MpiVariableSynchronizeDispatcher.cc
  MpiVariableSynchronizeDispatcher.h
  MpiBlockVariableSynchronizeDispatcher.cc
  MpiDirectSendrecvVariableSynchronizeDispatcher.cc
  MpiDirectSendrecvVariableSynchronizeDispatcher.h
  MpiLegacyVariableSynchronizeDispatcher.cc
  MpiLegacyVariableSynchronizeDispatcher.h
  MpiSerializeMessage.h
  MpiSerializeMessageList.h
  MpiTimerMng.cc
  MpiTimerMng.h
  MpiBatchMainFactory.cc
  MpiBatchMainFactory.h
  ArcaneMpi.h
  MpiDatatypeList.h
  MpiParallelMng.h
  MpiParallelDispatch.h
  MpiParallelNonBlockingCollective.h
  MpiParallelNonBlockingCollectiveDispatch.h
  MpiVariableSynchronizeDispatcher.h
  MpiSerializeMessage.h
  MpiSerializeMessageList.h
  MpiTimerMng.h
  MpiBatchMainFactory.h
  MpiAdapter.h
  MpiDatatype.h
  MpiLock.h
  MpiTimeInterval.h
  )
