/* Author : havep at Mon Jun 30 18:00:20 2008
 * Generated by createNew
 */


#ifndef PETSCSOLVERCONFIGRICHARDSONSERVICE_H
#define PETSCSOLVERCONFIGRICHARDSONSERVICE_H

#include <ALIEN/Kernels/PETSc/PETScPrecomp.h>
#include <ALIEN/Alien-ExternalPackagesPrecomp.h>

#include <ALIEN/Kernels/PETSc/LinearSolver/IPETScKSP.h>
#include <ALIEN/Kernels/PETSc/LinearSolver/IPETScPC.h>
#include <ALIEN/Kernels/PETSc/LinearSolver/PETScConfig.h>
#include <ALIEN/Kernels/PETSc/LinearSolver/PETScInitType.h>
#include <ALIEN/Kernels/PETSc/LinearSolver/PETScInternalLinearSolver.h>
#include <ALIEN/axl/PETScSolverConfigRichardson_axl.h>
#include <alien/core/backend/IInternalLinearSolverT.h>

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

namespace Alien {

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

class ALIEN_EXTERNALPACKAGES_EXPORT PETScSolverConfigRichardsonService
: public ArcanePETScSolverConfigRichardsonObject,
  public PETScConfig
{
 public:
  /** Constructeur de la classe */
#ifdef ALIEN_USE_ARCANE
  PETScSolverConfigRichardsonService(const Arcane::ServiceBuildInfo & sbi);
#endif

  PETScSolverConfigRichardsonService(
      Arccore::MessagePassing::IMessagePassingMng* parallel_mng,
      std::shared_ptr<IOptionsPETScSolverConfigRichardson> options);

  /** Destructeur de la classe */
  virtual ~PETScSolverConfigRichardsonService() {}
  
public:

  //! Initialisation
  void configure(KSP & ksp,
                 const ISpace& space,
                 const MatrixDistribution& distribution);
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

} // namespace Alien

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif //PETSCSOLVERCONFIGRICHARDSONSERVICE_H

