set( ARCANE_SOURCES
  AcceleratorCoreGlobal.h
  AcceleratorCore.cc
  AcceleratorRuntimeInitialisationInfo.cc
  AcceleratorRuntimeInitialisationInfo.h
  IAcceleratorMng.h
  AcceleratorMng.cc
  IReduceMemoryImpl.h
  IRunQueueRuntime.h
  IRunQueueStream.h
  Memory.h
  Runner.h
  Runner.cc
  RunCommand.h
  RunCommand.cc
  RunQueue.h
  RunQueue.cc
  RunQueueBuildInfo.h
  RunQueueImpl.h
  RunQueueImpl.cc
  RunQueueRuntime.cc
)
