// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
#ifndef ARCGEOSIM_TESTS_SERVICETESTS_ISERVICEVALIDATOR_H
#define ARCGEOSIM_TESTS_SERVICETESTS_ISERVICEVALIDATOR_H
/* Author : dipietrd at Wed Jan  2 15:41:26 2008
 * Generated by createNew
 * 
 * Service to validate some results
 * the service can be called at the end of the simulation by application
 */

class IServiceValidator
{
public:
  //! Constructor
  IServiceValidator() {}
  
  //! Destructor
  virtual ~IServiceValidator() { }
  
public:
  //! Initialize
  virtual void init() = 0 ;
  
  //! Run the validate test and return 0 if the validation is succesful
  virtual int validate() = 0 ;
};

#endif /* ARCGEOSIM_TESTS_SERVICETESTS_ISERVICEVALIDATOR_H */
