// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Arcane.Axl {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class ModuleT4 : ModuleT4Base {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("/*---------------------------------------------------------------------------*/\n/*---------------------------------------------------------------------------*/\n// #WARNING#: This file has been generated automatically. Do not edit.\n// Arcane version ");
            
            #line default
            #line hidden
            
            #line 9 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Version ));
            
            #line default
            #line hidden
            
            #line 9 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(" : ");
            
            #line default
            #line hidden
            
            #line 9 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DateTime.Now ));
            
            #line default
            #line hidden
            
            #line 9 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\n/*---------------------------------------------------------------------------*/\n/*---------------------------------------------------------------------------*/\n\n#ifndef ARCANE_MODULE_");
            
            #line default
            #line hidden
            
            #line 13 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName.ToUpper() ));
            
            #line default
            #line hidden
            
            #line 13 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("_H\n#define ARCANE_MODULE_");
            
            #line default
            #line hidden
            
            #line 14 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName.ToUpper() ));
            
            #line default
            #line hidden
            
            #line 14 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("_H\n\n/*---------------------------------------------------------------------------*/\n/*---------------------------------------------------------------------------*/\n\n#include \"arcane/VariableTypes.h\"\n#include \"arcane/EntryPoint.h\"\n#include \"arcane/ISubDomain.h\"\n#include \"arcane/ModuleBuildInfo.h\"\n#include \"arcane/ModuleFactory.h\"\n#include \"arcane/ServiceRegisterer.h\"\n#include \"arcane/BasicModule.h\"\n#include \"arcane/ServiceInfo.h\"\n\n/*---------------------------------------------------------------------------*/\n/*---------------------------------------------------------------------------*/\n\nARCANE_BEGIN_NAMESPACE\nclass ISubDomain;\nclass IModule;\nARCANE_END_NAMESPACE\n\n/*---------------------------------------------------------------------------*/\n/*---------------------------------------------------------------------------*/\n");
            
            #line default
            #line hidden
            
            #line 38 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  if (Xml.LesserThanVersionOne) { 
            
            #line default
            #line hidden
            
            #line 39 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\nARCANE_BEGIN_NAMESPACE\n \n/*---------------------------------------------------------------------------*/\n/*---------------------------------------------------------------------------*/\n");
            
            #line default
            #line hidden
            
            #line 44 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
 	}
	if(Xml.NamespaceMacroName != null) { 
            
            #line default
            #line hidden
            
            #line 46 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 47 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.NamespaceMacroName ));
            
            #line default
            #line hidden
            
            #line 47 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("_BEGIN_NAMESPACE\n\n/*---------------------------------------------------------------------------*/\n/*---------------------------------------------------------------------------*/\n");
            
            #line default
            #line hidden
            
            #line 51 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  } 
    if(Xml.NamespaceName != null) { 
            
            #line default
            #line hidden
            
            #line 53 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\nnamespace ");
            
            #line default
            #line hidden
            
            #line 54 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.NamespaceName ));
            
            #line default
            #line hidden
            
            #line 54 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(" {\n\n/*---------------------------------------------------------------------------*/\n/*---------------------------------------------------------------------------*/\n");
            
            #line default
            #line hidden
            
            #line 58 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  } 
            
            #line default
            #line hidden
            
            #line 59 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\nclass CaseOptions");
            
            #line default
            #line hidden
            
            #line 60 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName ));
            
            #line default
            #line hidden
            
            #line 60 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(";\n\n/*---------------------------------------------------------------------------*/\n/*---------------------------------------------------------------------------*/\n\n//! Generation de la classe de base du Module\nclass Arcane");
            
            #line default
            #line hidden
            
            #line 66 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName ));
            
            #line default
            #line hidden
            
            #line 66 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("Object\n  : public Arcane::BasicModule\n{\npublic:\n\n  static Arcane::IServiceInfo* serviceInfoCreateFunction(const Arcane::String& name)\n  {\n    Arcane::IServiceInfo* si = new Arcane::ServiceInfo(name, Arcane::VersionInfo(\"0.0\"),\n                                                       Arcane::IServiceInfo::Dim2 |\n                                                       Arcane::IServiceInfo::Dim3);\n    return si;\n  }\n\npublic:\n\n  Arcane");
            
            #line default
            #line hidden
            
            #line 81 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName ));
            
            #line default
            #line hidden
            
            #line 81 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("Object(const Arcane::ModuleBuildInfo& mb)\n    : Arcane::BasicModule(mb)\n");
            
            #line default
            #line hidden
            
            #line 83 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  if (Xml.Options.Count() > 0) { 
            
            #line default
            #line hidden
            
            #line 84 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("    , m_options(NULL)\n");
            
            #line default
            #line hidden
            
            #line 85 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  } 
            
            #line default
            #line hidden
            
            #line 86 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  foreach(var v in Module.Variables) { 
            
            #line default
            #line hidden
            
            #line 87 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("    , m_");
            
            #line default
            #line hidden
            
            #line 87 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( v.fieldname ));
            
            #line default
            #line hidden
            
            #line 87 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("(Arcane::VariableBuildInfo(this, \"");
            
            #line default
            #line hidden
            
            #line 87 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( v.name ));
            
            #line default
            #line hidden
            
            #line 87 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\"");
            
            #line default
            #line hidden
            
            #line 87 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"

      if(v.NbProperty > 0) { 
    
            
            #line default
            #line hidden
            
            #line 90 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(", Arcane::IVariable::P");
            
            #line default
            #line hidden
            
            #line 90 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( v.FirstProperty.ToString () ));
            
            #line default
            #line hidden
            
            #line 90 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
 
        foreach(var p in v.OthersProperties) {
    
            
            #line default
            #line hidden
            
            #line 93 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("| Arcane::IVariable::P");
            
            #line default
            #line hidden
            
            #line 93 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( p.ToString () ));
            
            #line default
            #line hidden
            
            #line 93 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"

        } 
      } 
            
            #line default
            #line hidden
            
            #line 96 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("))\n");
            
            #line default
            #line hidden
            
            #line 97 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  } 
            
            #line default
            #line hidden
            
            #line 98 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("  {\n");
            
            #line default
            #line hidden
            
            #line 99 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  if (Xml.Options.Count() > 0) { 
            
            #line default
            #line hidden
            
            #line 100 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("    m_options = new CaseOptions");
            
            #line default
            #line hidden
            
            #line 100 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName ));
            
            #line default
            #line hidden
            
            #line 100 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("(mb.m_sub_domain->caseMng());\n    m_options->setCaseModule(this);\n");
            
            #line default
            #line hidden
            
            #line 102 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  }

    foreach(var ep in Module.EntryPoints) { 
            
            #line default
            #line hidden
            
            #line 105 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("    addEntryPoint(this, \"");
            
            #line default
            #line hidden
            
            #line 105 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ep.name ));
            
            #line default
            #line hidden
            
            #line 105 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\", \n                  &Arcane");
            
            #line default
            #line hidden
            
            #line 106 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName ));
            
            #line default
            #line hidden
            
            #line 106 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("Object::");
            
            #line default
            #line hidden
            
            #line 106 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ep.methodname ));
            
            #line default
            #line hidden
            
            #line 106 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(",\n                  Arcane::IEntryPoint::");
            
            #line default
            #line hidden
            
            #line 107 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ep.@where.Name () ));
            
            #line default
            #line hidden
            
            #line 107 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(",\n                  Arcane::IEntryPoint::");
            
            #line default
            #line hidden
            
            #line 108 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ep.property.Name () ));
            
            #line default
            #line hidden
            
            #line 108 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(");\n");
            
            #line default
            #line hidden
            
            #line 109 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  } 
            
            #line default
            #line hidden
            
            #line 110 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("  }\n\n  virtual ~Arcane");
            
            #line default
            #line hidden
            
            #line 112 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName ));
            
            #line default
            #line hidden
            
            #line 112 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("Object()\n  {\n");
            
            #line default
            #line hidden
            
            #line 114 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  if (Xml.Options.Count() > 0) { 
            
            #line default
            #line hidden
            
            #line 115 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("    delete m_options;\n");
            
            #line default
            #line hidden
            
            #line 116 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  } 
            
            #line default
            #line hidden
            
            #line 117 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("  }\n\npublic:\n\n  //! points d'entrée\n");
            
            #line default
            #line hidden
            
            #line 122 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  foreach(var ep in Module.EntryPoints) { 
            
            #line default
            #line hidden
            
            #line 123 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("  virtual void ");
            
            #line default
            #line hidden
            
            #line 123 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ep.methodname ));
            
            #line default
            #line hidden
            
            #line 123 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("() = 0; // ");
            
            #line default
            #line hidden
            
            #line 123 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ep.methodname.ToClassName () ));
            
            #line default
            #line hidden
            
            #line 123 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 124 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  } 
            
            #line default
            #line hidden
            
            #line 125 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 126 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  if (Xml.Options.Count() > 0) { 
            
            #line default
            #line hidden
            
            #line 127 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("  //! Options du jeu de données du module\n  CaseOptions");
            
            #line default
            #line hidden
            
            #line 128 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName ));
            
            #line default
            #line hidden
            
            #line 128 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("* options() const { return m_options; }\n\nprivate:\n\n  //! Options du jeu de données du module\n  CaseOptions");
            
            #line default
            #line hidden
            
            #line 133 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName ));
            
            #line default
            #line hidden
            
            #line 133 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("* m_options;\n");
            
            #line default
            #line hidden
            
            #line 134 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  } 
            
            #line default
            #line hidden
            
            #line 135 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\nprotected:\n\n  //! Variables du module\n");
            
            #line default
            #line hidden
            
            #line 139 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  foreach(var v in Module.Variables) { 
      if(v.IsInFlow) { 
            
            #line default
            #line hidden
            
            #line 141 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("  const Arcane::");
            
            #line default
            #line hidden
            
            #line 141 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( v.ClassName ));
            
            #line default
            #line hidden
            
            #line 141 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(" m_");
            
            #line default
            #line hidden
            
            #line 141 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( v.fieldname ));
            
            #line default
            #line hidden
            
            #line 141 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 142 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
    } else { 
            
            #line default
            #line hidden
            
            #line 143 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("  Arcane::");
            
            #line default
            #line hidden
            
            #line 143 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( v.ClassName ));
            
            #line default
            #line hidden
            
            #line 143 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(" m_");
            
            #line default
            #line hidden
            
            #line 143 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( v.fieldname ));
            
            #line default
            #line hidden
            
            #line 143 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 144 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
    }
    } 
            
            #line default
            #line hidden
            
            #line 146 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("};\n\n/*---------------------------------------------------------------------------*/\n/*---------------------------------------------------------------------------*/\n\n#define ARCANE_REGISTER_MODULE_");
            
            #line default
            #line hidden
            
            #line 151 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName.ToUpper() ));
            
            #line default
            #line hidden
            
            #line 151 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("(class_name) \\\nextern \"C++\" ARCANE_EXPORT Arcane::IModuleFactoryInfo* \\\narcaneCreateModuleFactory");
            
            #line default
            #line hidden
            
            #line 153 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName ));
            
            #line default
            #line hidden
            
            #line 153 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("(Arcane::IServiceInfo* si) \\\n{ \\\n  return new Arcane::ModuleFactory(si,new Arcane::ModuleFactory2T< class_name > (\"");
            
            #line default
            #line hidden
            
            #line 155 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName ));
            
            #line default
            #line hidden
            
            #line 155 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\"),");
            
            #line default
            #line hidden
            
            #line 155 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Module.autoload.ToString ().ToLower () ));
            
            #line default
            #line hidden
            
            #line 155 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("); \\\n} \\\nArcane::ServiceRegisterer ARCANE_EXPORT globalModuleRegisterer");
            
            #line default
            #line hidden
            
            #line 157 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName ));
            
            #line default
            #line hidden
            
            #line 157 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("(arcaneCreateModuleFactory");
            
            #line default
            #line hidden
            
            #line 157 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName ));
            
            #line default
            #line hidden
            
            #line 157 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(",\"");
            
            #line default
            #line hidden
            
            #line 157 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.ClassName ));
            
            #line default
            #line hidden
            
            #line 157 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\")\n\n/*---------------------------------------------------------------------------*/\n/*---------------------------------------------------------------------------*/\n");
            
            #line default
            #line hidden
            
            #line 161 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  if(Xml.NamespaceMacroName != null) { 
            
            #line default
            #line hidden
            
            #line 162 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 163 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Xml.NamespaceMacroName ));
            
            #line default
            #line hidden
            
            #line 163 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("_END_NAMESPACE\n\n/*---------------------------------------------------------------------------*/\n/*---------------------------------------------------------------------------*/\n");
            
            #line default
            #line hidden
            
            #line 167 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  } 
    if(Xml.NamespaceName != null) { 
            
            #line default
            #line hidden
            
            #line 169 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\n}\n\n/*---------------------------------------------------------------------------*/\n/*---------------------------------------------------------------------------*/\n");
            
            #line default
            #line hidden
            
            #line 174 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  } 
	if (Xml.LesserThanVersionOne) { 
            
            #line default
            #line hidden
            
            #line 176 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\nARCANE_END_NAMESPACE\n \n/*---------------------------------------------------------------------------*/\n/*---------------------------------------------------------------------------*/\n");
            
            #line default
            #line hidden
            
            #line 181 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
  } 
            
            #line default
            #line hidden
            
            #line 182 "/work/irlin665_1/gaynor/ARCANE_OPTIONS_FINAL_WS/Arcane/arcane/src/arcane/axl/Arcane.Axl.T4/Arcane.Axl/T4.Module/ModuleT4.tt"
            this.Write("\n#endif\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        protected virtual void Initialize() {
        }
    }
    
    public class ModuleT4Base {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((this.formatProvider == null)) {
                        throw new global::System.ArgumentNullException("formatProvider");
                    }
                    this.formatProvider = value;
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
