// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
#ifndef ARCGEOSIM_EXPRESSIONS_IEXPRESSIONMNG_H
#define ARCGEOSIM_EXPRESSIONS_IEXPRESSIONMNG_H
/* Author : havep at Thu Oct 30 10:38:53 2008
 * Generated by createNew
 */

#include "Numerics/Expressions/IFunction.h"
#include <arcane/utils/UtilsTypes.h> // définition de Real et String

using namespace Arcane;

class IExpressionMng
{
public:
  /** Constructeur de la classe */
  IExpressionMng() 
    {
      ;
    }
  
  /** Destructeur de la classe */
  virtual ~IExpressionMng() { }
  
public:

  //! Initialisation
  virtual void init() = 0;

  //! Access to constante
  virtual Real constant(const String & name) const = 0;

  //! teste l'existence d'une constante de nom donné
  virtual const Real * constantLookup(const String & name) const = 0;

  //! Access to function
  virtual IFunction * function(const String & name) const = 0;

  // Méthodes a ajouter

};

#endif /* ARCGEOSIM_EXPRESSIONS_IEXPRESSIONMNG_H */
