// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
#ifndef ARCGEOSIM_EXPRESSIONS_IFUNCTION_H
#define ARCGEOSIM_EXPRESSIONS_IFUNCTION_H
/* Author : havep at Thu Oct 30 11:32:09 2008
 * Generated by createNew
 */

namespace Arcane { }
using namespace Arcane ;

#include "Numerics/Expressions/IIFunction.h"

class IFunction : public IIFunction
{
public:
  //! Constructeur de la classe
  IFunction() 
    : m_internal(NULL)
    {
      ;
    }
  
  //! Destructeur de la classe
  virtual ~IFunction() 
  { 
    // Deleting NULL is legal
    delete m_internal;
  }

public:
  //! Cast function
  /*! Return NULL if not initialized or bad casting */
  template<typename FunctionType>
  static FunctionType * cast(IFunction * f) {
    return dynamic_cast<FunctionType*>(f->m_internal);
  } 

  //! Cast const function
  /*! Return NULL if not initialized or bad casting */
  template<typename FunctionType>
  static const FunctionType * cast(const IFunction * f) {
    return dynamic_cast<const FunctionType*>(f->m_internal);
  }

protected:  
  //! Internal view of IFunction
  IIFunction * m_internal;
};

#endif /* ARCGEOSIM_EXPRESSIONS_IFUNCTION_H */
