/* Author : desrozis at Mon Mar 30 15:06:37 2009
 * Generated by createNew
 */

#ifndef IFPSOLVERIMPL_H
#define IFPSOLVERIMPL_H

#include <alien/utils/Precomp.h>
#include <alien/kernels/ifp/IFPSolverPrecomp.h>
#include <alien/kernels/ifp/IFPSolverBackEnd.h>
#include <alien/core/backend/LinearSolver.h>
#include <alien/kernels/ifp/linear_solver/IFPSolverProperty.h>
#include <alien/kernels/ifp/linear_solver/IFPInternalLinearSolver.h>

#include <ALIEN/axl/IFPLinearSolver_axl.h>
#include <alien/AlienIFPENSolversPrecomp.h>

namespace Alien {
/*---------------------------------------------------------------------------*/

class ALIEN_IFPEN_SOLVERS_EXPORT IFPLinearSolverService
    : public ArcaneIFPLinearSolverObject,
      public IFPInternalLinearSolver
{
 public:
 public:
/** Constructeur de la classe */

#ifdef ALIEN_USE_ARCANE
  IFPLinearSolverService(const Arcane::ServiceBuildInfo& sbi);
#endif
  IFPLinearSolverService(Arccore::MessagePassing::IMessagePassingMng* parallel_mng,
      std::shared_ptr<IOptionsIFPLinearSolver> options);

  /** Destructeur de la classe */
  virtual ~IFPLinearSolverService() {}

 public:
};

} // namespace Alien

#endif // IFPSOLVERIMPL_H
