/* Author : havep at Mon Jun 30 18:00:20 2008
 * Generated by createNew
 */


#ifndef PETSCSOLVERCONFIGBICGSTABSERVICE_H
#define PETSCSOLVERCONFIGBICGSTABSERVICE_H

#include <alien/Kernels/PETSc/PETScPrecomp.h>
#include <alien/AlienExternalPackagesPrecomp.h>

#include <alien/Kernels/PETSc/LinearSolver/IPETScKSP.h>
#include <alien/Kernels/PETSc/LinearSolver/IPETScPC.h>
#include <alien/Kernels/PETSc/LinearSolver/PETScConfig.h>
#include <alien/Kernels/PETSc/LinearSolver/PETScInitType.h>
#include <ALIEN/axl/PETScSolverConfigBiCGStab_axl.h>

namespace Alien {

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

class ALIEN_EXTERNAL_PACKAGES_EXPORT PETScSolverConfigBiCGStabService
: public ArcanePETScSolverConfigBiCGStabObject,
  public PETScConfig
{
 public:
  /** Constructeur de la classe */
#ifdef ALIEN_USE_ARCANE
  PETScSolverConfigBiCGStabService(const Arcane::ServiceBuildInfo & sbi);
#endif
  PETScSolverConfigBiCGStabService(
      Arccore::MessagePassing::IMessagePassingMng* parallel_mng,
      std::shared_ptr<IOptionsPETScSolverConfigBiCGStab> options);

  /** Destructeur de la classe */
  virtual ~PETScSolverConfigBiCGStabService() {}
  
public:

  //! Initialisation
  void configure(KSP & ksp,
                 const ISpace& space,
                 const MatrixDistribution& distribution);

};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

} // namespace Alien

#endif //PETSCSOLVERCONFIGBICGSTABSERVICE_H
/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/
