# NB: par defaut les packages sont cherches dans un repertoire 'packages' situe a l'endroit
#     du script d'appel de load_packages

macro(loadPackage)
  
  set(options ESSENTIAL)
  set(oneValueArgs NAME PATH)
  set(multiValueArgs)
  
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  
  # for find_package with Foo_ROOT
  cmake_policy(SET CMP0074 NEW)
  if (CMAKE_VERSION GREATER_EQUAL 3.27.1)
      cmake_policy(SET CMP0144 NEW)
  endif ()

  if(POLICY CMP0167)
      cmake_policy(SET CMP0167 OLD)
  endif()

  if(POLICY CMP0125)
      cmake_policy(SET CMP0125 NEW)
  endif()

  if(POLICY CMP0160)
      cmake_policy(SET CMP0160 OLD)
  endif()

  if(ARGS_UNPARSED_ARGUMENTS)
    logFatalError("unparsed arguments '${ARGS_UNPARSED_ARGUMENTS}'")
  endif()
  
  if(NOT ARGS_NAME) 
    logFatalError("load_package error, name is undefined")
  endif()

  if(NOT ARGS_PATH) 
#   get_filename_component(SELF_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)
    set(path ${INFRA_BUILDSYSTEM_PATH}/packages)
  else()
    if(IS_ABSOLUTE ${ARGS_PATH})
      set(path ${ARGS_PATH})
    else()
      get_filename_component(SELF_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)
      set(path ${SELF_DIR}/${ARGS_PATH})
    endif()
  endif()

#  if(NOT EXISTS ${path}/Find${ARGS_NAME}.cmake AND NOT ARGS_META)
#    logFatalError("Find${ARGS_NAME}.cmake is not found - check PATH")
#  endif()

  string(TOLOWER ${ARGS_NAME} target)
  string(TOUPPER ${ARGS_NAME} TARGET)

  if(ARGS_ESSENTIAL) 
    set(${target}_IS_ESSENTIAL ON)
  endif()
  
  if(NOT DEFINED ${target}_IS_DISABLED)
    set(${target}_IS_DISABLED OFF)
  endif()
  
  if(${${target}_IS_DISABLED})
    if(${${target}_IS_ESSENTIAL})
      logFatalError("package ${ARGS_NAME} is essential, can't be disabled") 
    endif()
  else()
    if(ARGS_META)
       logStatus("Args meta : ${ARGS_META}")
       logStatus("USE CMAKE CONFIG : ${${ARGS_NAME}_USE_CMAKE_CONFIG}")
       logStatus("${ARGS_NAME}_ROOT : ${${TARGET}_ROOT}")
       create_meta(NAME ${target})
    else()
    
       logStatus("Config path : ${path}/Find${ARGS_NAME}.cmake")
       logStatus("Args meta : ${ARGS_META}")
       logStatus("USE CMAKE CONFIG : ${${ARGS_NAME}_USE_CMAKE_CONFIG}")
       if(${ARGS_NAME}_USE_CMAKE_CONFIG AND NOT ARGS_META)
           logStatus("**********************USING CMAKE CONFIG")
            # Arccon
            # we use find_package now !
            if (ARGS_ESSENTIAL)
                find_package(${ARGS_NAME} REQUIRED)
            else ()
                find_package(${ARGS_NAME} QUIET)
            endif ()
            logStatus("FOUND : ${${ARGS_NAME}_FOUND}")
            if(${ARGS_NAME}_FOUND)
                # fix for package Arccon et Axlstar
                if (${ARGS_NAME} STREQUAL "Arccon")
                    set(ARCCON_FOUND ON)
                endif ()
                if (${ARGS_NAME} STREQUAL "Axlstar")
                    set(AXLSTAR_FOUND ON)
                endif ()
                if (${ARGS_NAME} STREQUAL "Arcane")
                    set(ARCANE_FOUND ON)
                    set(${target}_IS_LOADED ON)
                    set(target Arcane::arcane_full)
                endif ()
                if (${ARGS_NAME} STREQUAL "Arccore")
                    set(ARCCORE_FOUND ON)
                    set(${target}_IS_LOADED ON)
                    set(target Arccore::arccore_full)
                endif ()
                if (${ARGS_NAME} STREQUAL "ArcGeoSim")
                    set(ARCGEOSIM_FOUND ON)
                    set(${target}_IS_LOADED ON)
                    set(target ArcGeoSim::arcgeosim)
                endif ()
                if (${ARGS_NAME} STREQUAL "ArcGeoSimR")
                    set(ARCGEOSIMR_FOUND ON)
                    set(${target}_IS_LOADED ON)
                    set(target ArcGeoSim::arcgeosimr)
                endif ()
            endif()
      else()
        include(${path}/Find${ARGS_NAME}.cmake)
      endif()
      if(TARGET ${target})
         set(${target}_IS_LOADED ON)
         if(WIN32)
           copyAllDllFromTarget(${target})
         endif()
       elseif (TARGET ${ARGS_NAME})
           set(${target}_IS_LOADED ON)
           if (WIN32)
               copyAllDllFromTarget(${ARGS_NAME})
           endif ()
       elseif (TARGET ${ARGS_NAME}::${ARGS_NAME})
           set(${target}_IS_LOADED ON)
           if (WIN32)
               copyAllDllFromTarget(${ARGS_NAME}::${ARGS_NAME})
           endif ()
       elseif (TARGET arccon::${target})
           set(${target}_IS_LOADED ON)
           if (WIN32)
               copyAllDllFromTarget(arccon::${target})
           endif ()
       elseif (TARGET arccon::${ARGS_NAME})
           set(${target}_IS_LOADED ON)
           if (WIN32)
               copyAllDllFromTarget(arccon::${ARGS_NAME})
           endif ()
       elseif (TARGET arccon::${TARGET})
           set(${target}_IS_LOADED ON)
           if (WIN32)
               copyAllDllFromTarget(arccon::${TARGET})
           endif ()
      elseif(${TARGET}_FOUND)
	      set(${target}_IS_LOADED ON)
      elseif (${ARGS_NAME}_FOUND)
          set(${target}_IS_LOADED ON)
      else()
        if(${${target}_IS_ESSENTIAL})
          logFatalError("package ${ARGS_NAME} is essential but not found") 
        endif()
      endif()
    endif()
  endif()

  if (${${ARGS_NAME}_ROOT})
    logStatus("${ARGS_NAME}_ROOT : ${${ARGS_NAME}_ROOT}")
  elseif (${${TARGET}_ROOT})
      logStatus("${ARGS_NAME}_ROOT : ${${TARGET}_ROOT}")
  endif ()

  get_property(TARGETS GLOBAL PROPERTY ${PROJECT_NAME}_TARGETS)
  list(APPEND TARGETS ${target})
  list(REMOVE_DUPLICATES TARGETS)
  set_property(GLOBAL PROPERTY ${PROJECT_NAME}_TARGETS ${TARGETS})

  # handle Namespaces for ArcGeoSim
    if (${ARGS_NAME} STREQUAL "ArcGeoSim" OR ${ARGS_NAME} STREQUAL "ArcGeoSimR")
        string(TOLOWER "${ARGS_NAME}" target_name)
        if (NOT TARGET ${target_name} AND TARGET ArcGeoSim::${target_name})
            add_library(${target_name} ALIAS ArcGeoSim::${target_name})
        elseif (NOT TARGET ArcGeoSim::${target_name} AND TARGET ${target_name})
            add_library(ArcGeoSim::${target_name} ALIAS ${target_name})
        elseif (NOT TARGET ArcGeoSim::${target_name} AND NOT TARGET ${target_name})
            message(FATAL_ERROR "No ArcGeoSim target (ArcGeoSim::${target_name} or ${target_name}) can be found")
        endif ()
    endif ()
endmacro()
