#pragma once

#include <ALIEN/Utils/Precomp.h>

#ifdef WIN32
//#include <ALIEN/Utils/WinUtil.h>
#endif

#define PETSC_DESTROY_NEW
#define PETSC_KSPSETPCSIDE_NEW
#define PETSC_KSPSETOPERATORS_NEW
#define PETSC_KSPDESTROY_NEW
#define PETSC_MATDESTROY_NEW
#define PETSC_VIEWERDESTROY_NEW
#define PETSC_HAVE_KSPRICHARDSONSETSELFSCALE
#define PETSC_GETPCTYPE_NEW