message(STATUS "Looking for SuperLU")

find_path(SUPERLU_INCLUDE_DIRS superlu_defs.h)
find_library(SUPERLU_LIBRARIES superlu_dist_4.2)

message(STATUS "SUPERLU_LIBRARY=${SUPERLU_LIBRARY}")

MESSAGE(STATUS "SUPERLU_LIBRARIES = ${SUPERLU_LIBRARIES}")
MESSAGE(STATUS "SUPERLU_INCLUDE_DIRS = ${SUPERLU_INCLUDE_DIRS}")

set(SUPERLU_FOUND "NO")
if(SUPERLU_INCLUDE_DIRS AND SUPERLU_LIBRARIES)
  set(SUPERLU_FOUND "YES" )
  message(STATUS "SUPERU_FOUND=YES")
  arcane_add_package_library(superlu SUPERLU)
endif()
