set(ARCANE_SOURCES
  AlephKernel.cc
  AlephKernel.h
  AlephVector.cc
  AlephVector.h
  AlephMatrix.cc
  AlephMatrix.h
  AlephParams.cc
  AlephParams.h
  AlephOrdering.cc
  AlephOrdering.h
  AlephIndexing.cc
  AlephIndexing.h
  AlephTopology.cc
  AlephTopology.h
  AlephFactory.cc
  AlephKernel.h
  AlephVector.h
  AlephMatrix.h
  AlephParams.h
  AlephOrdering.h
  AlephIndexing.h
  AlephTopology.h
  Aleph.h
  AlephGlobal.h
  IAleph.h
  AlephKernel.h
  AlephVector.h
  AlephMatrix.h
  AlephParams.h
  IAlephFactory.h
  AlephOrdering.h
  AlephIndexing.h
  AlephTopology.h
  AlephInterface.h
  AlephTypesSolver.h
  )
