FIND_PATH(ITAC_INCLUDE_DIRS VT.h ${ARCANE_PACKAGE_ITAC_ROOT}/include)
FIND_LIBRARY(ITAC_LIBRARIES VT ${ARCANE_PACKAGE_ITAC_ROOT}/slib)

MESSAGE(STATUS "ITAC_INCLUDE_DIRS=${ITAC_INCLUDE_DIRS}")
MESSAGE(STATUS "ITAC_LIBRARIES=${ITAC_LIBRARIES}")

SET( ITAC_FOUND "NO" )
IF(ITAC_INCLUDE_DIRS)
  IF (ITAC_LIBRARIES)
    SET( ITAC_FOUND "YES" )
  ENDIF(ITAC_LIBRARIES)
ENDIF(ITAC_INCLUDE_DIRS)
