FIND_PATH(MATHLINK_INCLUDE_DIR mathlink.h)
FIND_LIBRARY(MATHLINK_LIBRARY ML64i3)

MESSAGE(STATUS "MATHLINK_INCLUDE_DIR=${MATHLINK_INCLUDE_DIR}")
MESSAGE(STATUS "MATHLINK_LIBRARY=${MATHLINK_LIBRARY}")

SET(MATHLINK_FOUND "NO")
IF(MATHLINK_INCLUDE_DIR)
  IF (MATHLINK_LIBRARY)
    SET( MATHLINK_FOUND "YES" )
  ENDIF(MATHLINK_LIBRARY)
ENDIF(MATHLINK_INCLUDE_DIR)
