info("${VT100_FG_GREEN}Looking for ${VT100_BOLD}SuperLU${VT100_RESET}")

find_path(SUPERLU_INCLUDE_DIRS superlu_defs.h)
find_library(SUPERLU_LIBRARIES superlu_dist_4.2)

info("${VT100_FG_GREEN}SUPERLU_LIBRARY=${VT100_BOLD}${SUPERLU_LIBRARY}${VT100_RESET}")

MESSAGE(STATUS "SUPERLU_LIBRARIES = ${SUPERLU_LIBRARIES}")
MESSAGE(STATUS "SUPERLU_INCLUDE_DIRS = ${SUPERLU_INCLUDE_DIRS}")

set(SUPERLU_FOUND "NO")
if(SUPERLU_INCLUDE_DIRS AND SUPERLU_LIBRARIES)
  set(SUPERLU_FOUND "YES" )
  info("${VT100_FG_GREEN}${VT100_BOLD}SUPERU_FOUND=YES${VT100_RESET}")
  arcane_add_package_library(superlu SUPERLU)
endif()
