#ifndef ALIEN_EXPRESSION_SOLVER_ILINEARSOLVERDDM_H
#define ALIEN_EXPRESSION_SOLVER_ILINEARSOLVERDDM_H
/* Author : desrozis at Mon Mar 30 15:43:55 2009
 * Generated by createNew
 */

#include <alien/utils/Precomp.h>
#include <alien/expression/solver/ILinearSolver.h>
/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

namespace Alien {

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/
/*! Linear solver interface
 * @brief describe API for linear solver.
 */
class ILinearSolverDDM : public ILinearSolver
{

 public:
  ILinearSolverDDM() {}

  virtual ~ILinearSolverDDM() {}

 public:
  virtual bool solve(const Alien::IMatrix& Ad, const Alien::IMatrix& An,
      const Alien::IVector& b, Alien::IVector& x) = 0;
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/
}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif /* ALIEN_EXPRESSION_SOLVER_ILINEARSOLVERDDM_H */
