set(SOURCES
  # On met ces fichiers en premier car ce sont les plus long à compiler
  MemoryCopier.cc
  MemoryCopierTpl1.cc
  MemoryCopierTpl2.cc
  MemoryCopierTpl3.cc
  MemoryCopierTpl4.cc

  AcceleratorGlobal.h
  AcceleratorGlobal.cc
  AcceleratorUtils.h
  AcceleratorInitializer.cc
  AcceleratorInitializer.h
  Atomic.h
  CommonCudaHipReduceImpl.h
  CommonCudaHipAtomicImpl.h
  CommonUtils.h
  CommonUtils.cc
  CooperativeWorkGroupLoopRange.h
  CooperativeWorkGroupLoopRange.cc
  GenericFilterer.h
  GenericFilterer.cc
  GenericPartitioner.h
  GenericPartitioner.cc
  GenericReducer.h
  GenericScanner.h
  GenericSorter.h
  KernelLauncher.h
  Initializer.cc
  LocalMemory.h
  MultiThreadAlgo.h
  MultiThreadAlgo.cc
  NumArrayViews.h
  NumArrayViews.cc
  Reduce.h
  RunCommandLaunch.h
  RunCommandLaunch.cc
  RunCommandLaunchImpl.h
  RunCommandLoop.h
  ScanImpl.h
  SpanViews.h
  WorkGroupLoopRange.h
  WorkGroupLoopRange.cc

  internal/AcceleratorMemoryCopier.h
  internal/Initializer.h
)
