set(SOURCES
  AcceleratorGlobal.h
  AcceleratorGlobal.cc
  AcceleratorUtils.h
  CommonCudaHipReduceImpl.h
  CommonCudaHipAtomicImpl.h
  CommonUtils.h
  CommonUtils.cc
  GenericFilterer.h
  GenericFilterer.cc
  GenericPartitioner.h
  GenericPartitioner.cc
  GenericReducer.h
  GenericScanner.h
  GenericSorter.h
  KernelLauncher.h
  LocalMemory.h
  MemoryCopier.cc
  MultiThreadAlgo.h
  MultiThreadAlgo.cc
  Reduce.h
  RunCommandLaunch.h
  RunCommandLaunch.cc
  RunCommandLaunchImpl.h
  RunCommandLoop.h
  ScanImpl.h
  WorkGroupLoopRange.h
  WorkGroupLoopRange.cc
)
