#ifndef ALIEN_PETSCSOLVERIMPL_PETSCINITTYPE_H
#define ALIEN_PETSCSOLVERIMPL_PETSCINITTYPE_H
/* Author : havep at Mon Mar  9 13:17:15 2009
 * Generated by createNew
 */

#include <ALIEN/Kernels/PETSc/PETScPrecomp.h>
#include <ALIEN/Kernels/PETSc/LinearSolver/PETScConfig.h>
#include "PETScInternalLinearSolver.h"

namespace Alien {
struct PETScInitType
{
  static void apply(const PETScConfig* iksp, KSP& ksp,
      const PETScInternalLinearSolver::InitType::eInit type);
};

} // namespace Alien
#endif /* ARCGEOSIM_NUMERICS_LINEARSOLVER_PETSCSOLVERIMPL_PETSCINITTYPE_H */
