
set(DOXYGEN_ALIASES
  "arcane{1}=\\ref Arcane::\\1 \\\"\\1\\\""
  "arccore{1}=\\ref Arccore::\\1 \\\"\\1\\\""
  "arcaneacc{1}=\\ref Arcane::Accelerator::\\1 \\\"\\1\\\""
  "arcanemat{1}=\\ref Arcane::Materials::\\1 \\\"\\1\\\""
  "pr{1}=[PR #\\1](https://github.com/arcaneframework/framework/pull/\\1)"
)
set(DOXYGEN_EXAMPLE_PATTERNS
  ""
)

set(DOXYGEN_GENERATE_LATEX
  "NO"
)
set(DOXYGEN_LATEX_CMD_NAME
  "latex"
)
set(DOXYGEN_LATEX_BIB_STYLE
  "plain"
)
set(DOXYGEN_PREDEFINED
  "DOXYGEN_DOC=1"
  "ARCCORE_BASE_EXPORT="
  "ARCCORE_COMMON_EXPORT="
  "ARCCORE_COLLECTION_EXPORT="
  "ARCCORE_ACCELERATOR_EXPORT="
  "ARCCORE_MESSAGEPASSING_EXPORT="
  "ARCANE_ALIGNAS_PACKED"
  "ARCANE_ALIGNAS"
  "ARCANE_BEGIN_NAMESPACE=namespace Arcane {"
  "ARCANE_END_NAMESPACE=}"
  "ARCANE_CORE_EXPORT="
  "ARCANE_ACCELERATOR_EXPORT="
  "ARCANE_ACCELERATOR_CORE_EXPORT="
  "ARCANE_UTILS_EXPORT="
  "ARCANE_IMPL_EXPORT="
  "ARCANE_GEOMETRY_EXPORT="
  "ARCCORE_HOST_DEVICE=__host__ __device__"
  "ARCCORE_DEPRECATED_2019(a)=[[deprecated(a)]]"
  "ARCCORE_DEPRECATED_2020(a)=[[deprecated(a)]]"
  "ARCCORE_DEPRECATED_2021(a)=[[deprecated(a)]]"
  "ARCCORE_DEPRECATED_REASON(a)=[[deprecated(a)]]"
  "ARCANE_DEPRECATED_REASON(a)=[[deprecated(a)]]"
)

set(DOXYGEN_EXPAND_AS_DEFINED
  "ARCANE_MATERIALS_EXPORT"
  "ARCANE_HAS_CXX11"
  "GEOMETRIC_BEGIN_NAMESPACE"
  "GEOMETRIC_END_NAMESPACE"
  "GEOMETRIC_BEGIN_NAMESPACE"
  "GEOMETRIC_END_NAMESPACE"
  "MATERIALS_BEGIN_NAMESPACE"
  "MATERIALS_END_NAMESPACE"
  "ARCCORE_GENERATE_MESSAGEPASSING_PROTOTYPE"
  "ARCCORE_NORETURN"
  "ARCCORE_DEFINE_REFERENCE_COUNTED_CLASS"
  "ARCCORE_DEFINE_ARRAY_PODTYPE"
)

