set(ARCANE_DOXYGEN_INPUT_USER
  ${ARCANE_SRC_PATH}/arcane/core
  ${ARCANE_SRC_PATH}/arcane/utils
  ${ARCANE_SRC_PATH}/arcane/core/datatype
  ${ARCANE_SRC_PATH}/arcane/core/parallel
  ${ARCANE_SRC_PATH}/arcane/geometry
  ${ARCANE_SRC_PATH}/arcane/accelerator/core
  ${ARCANE_SRC_PATH}/arcane/accelerator
  ${ARCANE_SRC_PATH}/arcane/launcher
  ${ARCANE_SRC_PATH}/arcane/core/materials
  ${ARCANE_SRC_PATH}/arcane/materials
  ${ARCANE_SRC_PATH}/arcane/hdf5
  ${ARCANE_SRC_PATH}/arcane/cartesianmesh
  ${ARCANESRCROOT}/doc/doc_common
  ${ARCANESRCROOT}/doc/doc_common/chap_news
  ${ARCANESRCROOT}/doc/doc_common/chap_build_install
  ${ARCANESRCROOT}/doc/doc_common/chap_build_install/subchap_prerequisites
  ${ARCANESRCROOT}/doc/doc_user
  ${ARCANESRCROOT}/doc/doc_user/chap_core_types
  ${ARCANESRCROOT}/doc/doc_user/chap_core_types/subchap_axl
  ${ARCANESRCROOT}/doc/doc_user/chap_core_types/subchap_axl/subchap_caseoptions
  ${ARCANESRCROOT}/doc/doc_user/chap_debug_perf
  ${ARCANESRCROOT}/doc/doc_user/chap_debug_perf/subchap_profiling
  ${ARCANESRCROOT}/doc/doc_user/chap_entities
  ${ARCANESRCROOT}/doc/doc_user/chap_entities/subchap_amr_cartesianmesh
  ${ARCANESRCROOT}/doc/doc_user/chap_examples
  ${ARCANESRCROOT}/doc/doc_user/chap_examples/subchap_simple_example
  ${ARCANESRCROOT}/doc/doc_user/chap_examples/subchap_concret_example
  ${ARCANESRCROOT}/doc/doc_user/chap_execution
  ${ARCANESRCROOT}/doc/doc_user/chap_general
  ${ARCANESRCROOT}/doc/doc_user/chap_getting_started
  ${ARCANESRCROOT}/doc/doc_user/chap_io
  ${ARCANESRCROOT}/doc/doc_user/chap_io/subchap_timehistory
  ${ARCANESRCROOT}/doc/doc_user/chap_materials
  ${ARCANESRCROOT}/doc/doc_user/chap_parallel
  ${ARCANESRCROOT}/doc/doc_user/chap_parallel/subchap_shmem
  ${ARCANESRCROOT}/doc/doc_user/chap_acceleratorapi
  ${ARCANESRCROOT}/doc/doc_user/chap_services_modules
  ${ARCANESRCROOT}/doc/doc_user/chap_services_modules/subchap_simplecsvoutput
  ${ARCANESRCROOT}/doc/doc_user/chap_services_modules/subchap_simplecsvcomparator
  ${ARCANESRCROOT}/doc/doc_user/chap_wrapping
  ${ARCANESRCROOT}/doc/doc_user/chap_wrapping/subchap_csharp
  ${ARCANESRCROOT}/doc/doc_user/chap_wrapping/subchap_python
  ${ARCANESRCROOT}/tutorial
  ${ARCANESRCROOT}/tutorial/microhydro
  ${ARCANESRCROOT}/tutorial/poisson
  ${ARCANESRCROOT}/tutorial/helloworld
  ${DOC_OUTPUT_DIR}/share/axl/dox
  ${ARCANE_ADDITIONAL_DOC_PATH}
  ${Arccore_ROOT}/src/base/arccore/base
  ${Arccore_ROOT}/src/collections/arccore/collections
  ${Arccore_ROOT}/src/concurrency/arccore/concurrency
  ${Arccore_ROOT}/src/common/arccore/common
  ${Arccore_ROOT}/src/common/arccore/common/accelerator
  ${Arccore_ROOT}/src/accelerator/arccore/accelerator
  ${Arccore_ROOT}/src/trace/arccore/trace
  ${Arccore_ROOT}/src/message_passing/arccore/message_passing
  ${Arccore_ROOT}/src/message_passing_mpi/arccore/message_passing_mpi
  ${Arccore_ROOT}/src/serialize/arccore/serialize
  ${ARCANE_CEA_SOURCE_PATH}/src/arcane/cea
)