// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
#include "Mesh/GroupCreator/GroupCreatorModule.h"
/* Author : michela at Thu Mar 12 09:50:50 2009
 * Generated by createNew
 */

#include <arcane/ITimeLoopMng.h>

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

void
GroupCreatorModule::
init()
{
  info() << __PRETTY_FUNCTION__;
  
  m_group_creator = options()->groupCreator();
  
  m_group_creator->init(); 
}

/*---------------------------------------------------------------------------*/

void
GroupCreatorModule::
computeGroupsInit()
{
  computeGroups();
}

/*---------------------------------------------------------------------------*/

void
GroupCreatorModule::
computeGroups()
{
  info() << __PRETTY_FUNCTION__;
  
  m_group_creator->apply();
}

/*---------------------------------------------------------------------------*/

void
GroupCreatorModule::
restore()
{
  info() << __PRETTY_FUNCTION__;
}

/*---------------------------------------------------------------------------*/

void
GroupCreatorModule::
stopLoop()
{
  info() << __PRETTY_FUNCTION__;

  subDomain()->timeLoopMng()->stopComputeLoop(true);
}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

using namespace Arcane;

ARCANE_REGISTER_MODULE_GROUPCREATOR(GroupCreatorModule);
