name: ci-ifpen_linux_gimkl-2018b_by-components_external

on:
  push:
    branches: [ main, dev/ci_ifpen ]
  pull_request:
    branches: [ main, dev/ci_ifpen ]
  workflow_dispatch:
    branches: [ main, dev/ci_ifpen ]

env:
  # Arcane
  ARCANE_BUILD_DIR: /__w/framework/arcane_build
  ARCANE_INSTALL_DIR: /__w/framework/arcane_install
  ARCANE_SOURCE_DIR: /__w/framework/arcane
  # Arccon
  ARCCON_BUILD_DIR: /__w/framework/arccon_build
  ARCCON_INSTALL_DIR: /__w/framework/arccon_install
  ARCCON_SOURCE_DIR: /__w/framework/arccon
  # Arccore
  ARCCORE_BUILD_DIR: /__w/framework/arccore_build
  ARCCORE_INSTALL_DIR: /__w/framework/arccore_install
  ARCCORE_SOURCE_DIR: /__w/framework/arccore
  # ArcDependencies
  ARCDEPENDENCIES_BUILD_DIR: /__w/framework/arcdependencies_build
  ARCDEPENDENCIES_INSTALL_DIR: /__w/framework/arcdependencies_install
  ARCDEPENDENCIES_SOURCE_DIR: /__w/framework/arcdependencies
  # Axlstar
  AXLSTAR_BUILD_DIR: /__w/framework/axlstar_build
  AXLSTAR_INSTALL_DIR: /__w/framework/axlstar_install
  AXLSTAR_SOURCE_DIR: /__w/framework/axlstar
  # CMake
  CM_BUILD_TYPE: Debug
  # CTest
  CT_OPTS: --output-on-failure

jobs:
  arccon-install:
    name: arccon-install-${{matrix.config.name}}
    runs-on: ubuntu-latest
    container: ${{matrix.config.container}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "el7",
            container: "arcaneframework/centos-gimkl-2018b-arcane:7-latest",
          }
          - {
            name: "el8",
            container: "arcaneframework/rockylinux-gimkl-2018b-arcane:8-latest",
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/arccon
          path: arccon
          ref: main
          submodules: true
      - name: Configure
        shell: bash
        run: |
          cmake -S ${{ env.ARCCON_SOURCE_DIR }} -B ${{ env.ARCCON_BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.ARCCON_INSTALL_DIR }}
      - name: Build
        shell: bash
        run: |
          cmake --build ${{ env.ARCCON_BUILD_DIR }}
      - name: Install
        shell: bash
        run: |
          cmake --install ${{ env.ARCCON_BUILD_DIR }}
      - name: Upload install artifact
        uses: actions/upload-artifact@v2
        with:
          name: arccon-install-artifact
          path: |
            ${{ env.ARCCON_INSTALL_DIR }}
          retention-days: 1

#  arccore-install:
#    needs: [arccon-install-${{matrix.config.name}}]
#    name: arccore-install-${{matrix.config.name}}
#    runs-on: ubuntu-latest
#    container: ${{matrix.config.container}}
#    strategy:
#      fail-fast: false
#      matrix:
#        config:
#          - {
#            name: "el7",
#            container: "arcaneframework/centos-gimkl-2018b-arcane:7-latest",
#          }
#          - {
#            name: "el8",
#            container: "arcaneframework/rockylinux-gimkl-2018b-arcane:8-latest",
#          }
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          repository: ${{ github.repository_owner }}/arccore
#          path: arccore
#          ref: main
#          submodules: true
#      - name: Download arccon install artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: arccon-install-artifact
#      - name: Configure
#        shell: bash
#        run: |
#          cmake -S ${{ env.ARCCORE_SOURCE_DIR }} -B ${{ env.ARCCORE_BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.ARCCORE_INSTALL_DIR }} -DArccon_DIR=${{ env.ARCCON_INSTALL_DIR }}/share/cmake/Arccon -DBUILD_SHARED_LIBS=ON
#      - name: Build
#        shell: bash
#        run: |
#          cmake --build ${{ env.ARCCORE_BUILD_DIR }}
#      - name: Install
#        shell: bash
#        run: |
#          cmake --install ${{ env.ARCCORE_BUILD_DIR }}
#      - name: Upload build artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: arccore-build-artifact
#          path: |
#            ${{ env.ARCCORE_BUILD_DIR }}
#            !${{ env.ARCCORE_BUILD_DIR }}/**/*.dir
#          retention-days: 1
#      - name: Upload install artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: arccore-install-artifact
#          path: |
#            ${{ env.ARCCORE_INSTALL_DIR }}
#          retention-days: 1
#
#  arcdependencies-install:
#    needs: [arccon-install-${{matrix.config.name}}]
#    name: arcdependencies-install-${{matrix.config.name}}
#    runs-on: ubuntu-latest
#    container: ${{matrix.config.container}}
#    strategy:
#      fail-fast: false
#      matrix:
#        config:
#          - {
#            name: "el7",
#            container: "arcaneframework/centos-gimkl-2018b-arcane:7-latest",
#          }
#          - {
#            name: "el8",
#            container: "arcaneframework/rockylinux-gimkl-2018b-arcane:8-latest",
#          }
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          repository: ${{ github.repository_owner }}/arcdependencies
#          path: arcdependencies
#          ref: main
#          submodules: true
#      - name: Download arccon install artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: arccon-install-artifact
#      - name: Configure
#        shell: bash
#        run: |
#          cmake -S ${{ env.ARCDEPENDENCIES_SOURCE_DIR }} -B ${{ env.ARCDEPENDENCIES_BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.ARCDEPENDENCIES_INSTALL_DIR }} -DArccon_DIR=${{ env.ARCCON_INSTALL_DIR }}/share/cmake/Arccon
#      - name: Build
#        shell: bash
#        run: |
#          cmake --build ${{ env.ARCDEPENDENCIES_BUILD_DIR }}
#      - name: Install
#        shell: bash
#        run: |
#          cmake --install ${{ env.ARCDEPENDENCIES_BUILD_DIR }}
#      - name: Upload install artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: arcdependencies-install-artifact
#          path: |
#            ${{ env.ARCDEPENDENCIES_INSTALL_DIR }}
#          retention-days: 1
#
#  axlstar-install:
#    needs: [ardependencies-install-${{matrix.config.name}}]
#    name: axlstar-install-${{matrix.config.name}}
#    runs-on: ubuntu-latest
#    container: ${{matrix.config.container}}
#    strategy:
#      fail-fast: false
#      matrix:
#        config:
#          - {
#            name: "el7",
#            container: "arcaneframework/centos-gimkl-2018b-arcane:7-latest",
#          }
#          - {
#            name: "el8",
#            container: "arcaneframework/rockylinux-gimkl-2018b-arcane:8-latest",
#          }
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          repository: ${{ github.repository_owner }}/axlstar
#          path: axlstar
#          ref: main
#          submodules: true
#      - name: Download arcdependencies install artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: arcdependencies-install-artifact
#      - name: Configure
#        shell: bash
#        run: |
#          cmake -S ${{ env.AXLSTAR_SOURCE_DIR }} -B ${{ env.AXLSTAR_BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.AXLSTAR_INSTALL_DIR }} -DArcDependencies_DIR=${{ env.ARCDEPENDENCIES_INSTALL_DIR }}/share/cmake/ArcDependencies
#      - name: Build
#        shell: bash
#        run: |
#          cmake --build ${{ env.AXLSTAR_BUILD_DIR }}
#      - name: Install
#        shell: bash
#        run: |
#          cmake --install ${{ env.AXLSTAR_BUILD_DIR }}
#      - name: Upload install artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: axlstar-install-artifact
#          path: |
#            ${{ env.AXLSTAR_INSTALL_DIR }}
#          retention-days: 1
#
#  arcane-install:
#    needs: [arccon-install-${{matrix.config.name}}, arccore-install-${{matrix.config.name}}, arcdependencies-install-${{matrix.config.name}}, axlstar-install-${{matrix.config.name}}]
#    name: arcane-install-${{matrix.config.name}}
#    runs-on: ubuntu-latest
#    container: ${{matrix.config.container}}
#    strategy:
#      fail-fast: false
#      matrix:
#        config:
#          - {
#            name: "el7",
#            container: "arcaneframework/centos-gimkl-2018b-arcane:7-latest",
#          }
#          - {
#            name: "el8",
#            container: "arcaneframework/rockylinux-gimkl-2018b-arcane:8-latest",
#          }
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          path: arcane
#          submodules: true
#      - name: Download arccon install artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: arccon-install-artifact
#      - name: Download arccore install artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: arccore-install-artifact
#      - name: Download arcdependencies install artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: arcdependencies-install-artifact
#      - name: Download axlstar install artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: axlstar-install-artifact
#      - name: Configure
#        shell: bash
#        run: |
#          cmake -S ${{ env.ARCANE_SOURCE_DIR }} -B ${{ env.ARCANE_BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.ARCANE_INSTALL_DIR }} -DArccon_DIR=${{ env.ARCCON_INSTALL_DIR }}/share/cmake/Arccon -DArccore_DIR=${{ env.ARCCORE_INSTALL_DIR }}/lib/cmake/Arccore -DAxlstar_DIR=${{ env.AXLSTAR_INSTALL_DIR }}/share/cmake/Axlstar -DArcDependencies_DIR=${{ env.ARCDEPENDENCIES_INSTALL_DIR }}/share/cmake/ArcDependencies -DBUILD_SHARED_LIBS=ON -DARCANE_DEFAULT_PARTITIONER=Metis -DARCANE_WANT_TOTALVIEW=ON -DARCANE_WANT_LIBXML2=ON -DARCANE_WANT_LEGACY_CONNECTIVITY=OFF -DARCANE_WANT_CHECK=OFF -DARCANE_WANT_ARCCON_EXPORT_TARGET=OFF
#      - name: Build
#        shell: bash
#        run: |
#          cmake --build ${{ env.ARCANE_BUILD_DIR }}
#      - name: Install
#        shell: bash
#        run: |
#          cmake --install ${{ env.ARCANE_BUILD_DIR }}
#      - name: Upload build artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: arcane-build-artifact
#          path: |
#            ${{ env.ARCANE_BUILD_DIR }}
#            !${{ env.ARCANE_BUILD_DIR }}/**/*.dir
#          retention-days: 1
#
#  arccore-test:
#    needs: [arccore-install-${{matrix.config.name}}]
#    name: arccore-test-${{matrix.config.name}}
#    runs-on: ubuntu-latest
#    container: ${{matrix.config.container}}
#    strategy:
#      fail-fast: false
#      matrix:
#        config:
#          - {
#            name: "el7",
#            container: "arcaneframework/centos-gimkl-2018b-arcane:7-latest",
#          }
#          - {
#            name: "el8",
#            container: "arcaneframework/rockylinux-gimkl-2018b-arcane:8-latest",
#          }
#    steps:
#      - name: Download arccore build artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: arccore-build-artifact
#      - name: Test
#        shell: bash
#        run: |
#          cd ${{ env.ARCCORE_BUILD_DIR }}
#          ctest ${{ env.CT_OPTS }}
#
#  arcane-test:
#    needs: [arcane-install-${{matrix.config.name}}]
#    name: arcane-test-${{matrix.config.name}}
#    runs-on: ubuntu-latest
#    container: ${{matrix.config.container}}
#    strategy:
#      fail-fast: false
#      matrix:
#        config:
#          - {
#            name: "el7",
#            container: "arcaneframework/centos-gimkl-2018b-arcane:7-latest",
#          }
#          - {
#            name: "el8",
#            container: "arcaneframework/rockylinux-gimkl-2018b-arcane:8-latest",
#          }
#    steps:
#      - name: Download arcane build artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: arcane-build-artifact
#      - name: Download arccore install artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: arccore-install-artifact
#      - name: Download axlstar install artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: axlstar-install-artifact
#      - name: Test
#        shell: bash
#        run: |
#          cd ${{ env.ARCANE_BUILD_DIR }}
#          ctest ${{ env.CT_OPTS }}
