name: ci-ifpen_linux_el8_foss-2018b_by-components_external

on:
  push:
    branches: [ main, dev/cea, dev/ifpen, dev/ci_ifpen ]
  pull_request:
    branches: [ main, dev/cea, dev/ifpen, dev/ci_ifpen ]
  workflow_dispatch:
    branches: [ main, dev/cea, dev/ifpen, dev/ci_ifpen ]

env:
  # Arcane
  ARCANE_BUILD_DIR: /__w/framework/framework/arcane_build
  ARCANE_INSTALL_DIR: /__w/framework/framework/arcane_install
  ARCANE_SOURCE_DIR: /__w/framework/framework/arcane
  # Arccon
  ARCCON_BUILD_DIR: /__w/framework/framework/arccon_build
  ARCCON_INSTALL_DIR: /__w/framework/framework/arccon_install
  ARCCON_SOURCE_DIR: /__w/framework/framework/arccon
  # Arccore
  ARCCORE_BUILD_DIR: /__w/framework/framework/arccore_build
  ARCCORE_INSTALL_DIR: /__w/framework/framework/arccore_install
  ARCCORE_SOURCE_DIR: /__w/framework/framework/arccore
  # ArcDependencies
  ARCDEPENDENCIES_BUILD_DIR: /__w/framework/framework/arcdependencies_build
  ARCDEPENDENCIES_INSTALL_DIR: /__w/framework/framework/arcdependencies_install
  ARCDEPENDENCIES_SOURCE_DIR: /__w/framework/framework/arcdependencies
  # Axlstar
  AXLSTAR_BUILD_DIR: /__w/framework/framework/axlstar_build
  AXLSTAR_INSTALL_DIR: /__w/framework/framework/axlstar_install
  AXLSTAR_SOURCE_DIR: /__w/framework/framework/axlstar
  # CMake
  CM_BUILD_TYPE: Debug
  # CTest
  CT_OPTS: "--output-on-failure"

jobs:
  arccon-install:
    name: arccon-install
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/arcaneframework/rockylinux-foss-2018b-arcane:8-latest
      credentials:
        username: ${{ secrets.ci_ifpen_read_packages_username }}
        password: ${{ secrets.ci_ifpen_read_packages_password }}
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: arcaneframework/arccon
          path: ${{ env.ARCCON_SOURCE_DIR }}
          ref: main
      - name: Configure
        shell: bash
        run: |
          source /env.sh
          cmake -S ${{ env.ARCCON_SOURCE_DIR }} -B ${{ env.ARCCON_BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.ARCCON_INSTALL_DIR }}
      - name: Build
        shell: bash
        run: |
          source /env.sh
          cmake --build ${{ env.ARCCON_BUILD_DIR }}
      - name: Install
        shell: bash
        run: |
          source /env.sh
          cmake --install ${{ env.ARCCON_BUILD_DIR }}
      - name: Tar install artifact
        shell: bash
        run: |
          tar cf arccon-install-artifact.tar ${{ env.ARCCON_INSTALL_DIR }}
      - name: Upload install artifact
        uses: actions/upload-artifact@v2
        with:
          name: arccon-install-artifact
          path: |
            arccon-install-artifact.tar
          retention-days: 1

  arccore-install:
    needs:
      - arccon-install
    name: arccore-install
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/arcaneframework/rockylinux-foss-2018b-arcane:8-latest
      credentials:
        username: ${{ secrets.ci_ifpen_read_packages_username }}
        password: ${{ secrets.ci_ifpen_read_packages_password }}
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: arcaneframework/arccore
          path: ${{ env.ARCCORE_SOURCE_DIR }}
          ref: main
      - name: Download arccon install artifact
        uses: actions/download-artifact@v2
        with:
          name: arccon-install-artifact
      - name: Untar arccon install artifact
        shell: bash
        run: |
          tar xf arccon-install-artifact.tar -C /
      - name: Configure
        shell: bash
        run: |
          source /env.sh
          cmake -S ${{ env.ARCCORE_SOURCE_DIR }} -B ${{ env.ARCCORE_BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.ARCCORE_INSTALL_DIR }} -DArccon_DIR=${{ env.ARCCON_INSTALL_DIR }}/share/cmake/Arccon -DBUILD_SHARED_LIBS=ON
      - name: Build
        shell: bash
        run: |
          source /env.sh
          cmake --build ${{ env.ARCCORE_BUILD_DIR }}
      - name: Install
        shell: bash
        run: |
          source /env.sh
          cmake --install ${{ env.ARCCORE_BUILD_DIR }}
      - name: Tar build artifact
        shell: bash
        run: |
          tar cf arccore-build-artifact.tar ${{ env.ARCCORE_BUILD_DIR }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: arccore-build-artifact
          path: |
            arccore-build-artifact.tar
          retention-days: 1
      - name: Tar install artifact
        shell: bash
        run: |
          tar cf arccore-install-artifact.tar ${{ env.ARCCORE_INSTALL_DIR }}
      - name: Upload install artifact
        uses: actions/upload-artifact@v2
        with:
          name: arccore-install-artifact
          path: |
            arccore-install-artifact.tar
          retention-days: 1

  arcdependencies-install:
    needs:
      - arccon-install
    name: arcdependencies-install
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/arcaneframework/rockylinux-foss-2018b-arcane:8-latest
      credentials:
        username: ${{ secrets.ci_ifpen_read_packages_username }}
        password: ${{ secrets.ci_ifpen_read_packages_password }}
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: arcaneframework/dependencies
          path: ${{ env.ARCDEPENDENCIES_SOURCE_DIR }}
          ref: main
      - name: Download arccon install artifact
        uses: actions/download-artifact@v2
        with:
          name: arccon-install-artifact
      - name: Untar arccon install artifact
        shell: bash
        run: |
          tar tf arccon-install-artifact.tar
          tar xf arccon-install-artifact.tar -C /
      - name: Configure
        shell: bash
        run: |
          source /env.sh
          cmake -S ${{ env.ARCDEPENDENCIES_SOURCE_DIR }} -B ${{ env.ARCDEPENDENCIES_BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.ARCDEPENDENCIES_INSTALL_DIR }} -DArccon_DIR=${{ env.ARCCON_INSTALL_DIR }}/share/cmake/Arccon
      - name: Build
        shell: bash
        run: |
          source /env.sh
          cmake --build ${{ env.ARCDEPENDENCIES_BUILD_DIR }}
      - name: Install
        shell: bash
        run: |
          source /env.sh
          cmake --install ${{ env.ARCDEPENDENCIES_BUILD_DIR }}
      - name: Tar install ariftact
        shell: bash
        run: |
          tar cf arcdependencies-install-artifact.tar ${{ env.ARCDEPENDENCIES_INSTALL_DIR }}
      - name: Upload install artifact
        uses: actions/upload-artifact@v2
        with:
          name: arcdependencies-install-artifact
          path: |
            arcdependencies-install-artifact.tar
          retention-days: 1

  axlstar-install:
    needs:
      - arccon-install
      - arcdependencies-install
    name: axlstar-install
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/arcaneframework/rockylinux-foss-2018b-arcane:8-latest
      credentials:
        username: ${{ secrets.ci_ifpen_read_packages_username }}
        password: ${{ secrets.ci_ifpen_read_packages_password }}
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: arcaneframework/axlstar
          path: ${{ env.AXLSTAR_SOURCE_DIR }}
          ref: main
      - name: Download arccon install artifact
        uses: actions/download-artifact@v2
        with:
          name: arccon-install-artifact
      - name: Untar arccon install artifact
        shell: bash
        run: |
          tar xf arccon-install-artifact.tar -C /
      - name: Download arcdependencies install artifact
        uses: actions/download-artifact@v2
        with:
          name: arcdependencies-install-artifact
      - name: Untar arcdependencies install artifact
        shell: bash
        run: |
          tar xf arcdependencies-install-artifact.tar -C /
      - name: Configure
        shell: bash
        run: |
          source /env.sh
          cmake -S ${{ env.AXLSTAR_SOURCE_DIR }} -B ${{ env.AXLSTAR_BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.AXLSTAR_INSTALL_DIR }} -DArccon_DIR=${{ env.ARCCON_INSTALL_DIR }}/share/cmake/Arccon -DArcDependencies_DIR=${{ env.ARCDEPENDENCIES_INSTALL_DIR }}/share/cmake/ArcDependencies
      - name: Build
        shell: bash
        run: |
          source /env.sh
          cmake --build ${{ env.AXLSTAR_BUILD_DIR }}
      - name: Install
        shell: bash
        run: |
          source /env.sh
          cmake --install ${{ env.AXLSTAR_BUILD_DIR }}
      - name: Tar install artifact
        shell: bash
        run: |
          tar cf axlstar-install-artifact.tar ${{ env.AXLSTAR_INSTALL_DIR }}
      - name: Upload install artifact
        uses: actions/upload-artifact@v2
        with:
          name: axlstar-install-artifact
          path: |
            axlstar-install-artifact.tar
          retention-days: 1

  arcane-install:
    needs:
      - arccon-install
      - arccore-install
      - arcdependencies-install
      - axlstar-install
    name: arcane-install
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/arcaneframework/rockylinux-foss-2018b-arcane:8-latest
      credentials:
        username: ${{ secrets.ci_ifpen_read_packages_username }}
        password: ${{ secrets.ci_ifpen_read_packages_password }}
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.ARCANE_SOURCE_DIR }}
      - name: Download arccon install artifact
        uses: actions/download-artifact@v2
        with:
          name: arccon-install-artifact
      - name: Untar arccon install artifact
        shell: bash
        run: |
          tar xf arccon-install-artifact.tar -C /
      - name: Download arccore install artifact
        uses: actions/download-artifact@v2
        with:
          name: arccore-install-artifact
      - name: Untar arccore install artifact
        shell: bash
        run: |
          tar xf arccore-install-artifact.tar -C /
      - name: Download arcdependencies install artifact
        uses: actions/download-artifact@v2
        with:
          name: arcdependencies-install-artifact
      - name: Untar arcdependencies install artifact
        shell: bash
        run: |
          tar xf arcdependencies-install-artifact.tar -C /
      - name: Download axlstar install artifact
        uses: actions/download-artifact@v2
        with:
          name: axlstar-install-artifact
      - name: Untar axlstar install artifact
        shell: bash
        run: |
          tar xf axlstar-install-artifact.tar -C /
      - name: Configure
        shell: bash
        run: |
          source /env.sh
          cmake -S ${{ env.ARCANE_SOURCE_DIR }}/arcane -B ${{ env.ARCANE_BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.ARCANE_INSTALL_DIR }} -DArccon_DIR=${{ env.ARCCON_INSTALL_DIR }}/share/cmake/Arccon -DArccore_DIR=${{ env.ARCCORE_INSTALL_DIR }}/lib/cmake/Arccore -DAxlstar_DIR=${{ env.AXLSTAR_INSTALL_DIR }}/share/cmake/Axlstar -DArcDependencies_DIR=${{ env.ARCDEPENDENCIES_INSTALL_DIR }}/share/cmake/ArcDependencies -DBUILD_SHARED_LIBS=ON -DARCANE_DEFAULT_PARTITIONER=Metis -DARCANE_WANT_TOTALVIEW=ON -DARCANE_WANT_LIBXML2=ON -DARCANE_WANT_LEGACY_CONNECTIVITY=OFF -DARCANE_WANT_CHECK=OFF -DARCANE_WANT_ARCCON_EXPORT_TARGET=OFF
      - name: Build
        shell: bash
        run: |
          source /env.sh
          cmake --build ${{ env.ARCANE_BUILD_DIR }}
      - name: Install
        shell: bash
        run: |
          source /env.sh
          cmake --install ${{ env.ARCANE_BUILD_DIR }}
      - name: Tar build artifact
        shell: bash
        run: |
          tar cf arcane-build-artifact.tar ${{ env.ARCANE_BUILD_DIR }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: arcane-build-artifact
          path: |
            arcane-build-artifact.tar
          retention-days: 1

  arccore-test:
    needs:
      - arccon-install
      - arccore-install
    name: arccore-test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/arcaneframework/rockylinux-foss-2018b-arcane:8-latest
      credentials:
        username: ${{ secrets.ci_ifpen_read_packages_username }}
        password: ${{ secrets.ci_ifpen_read_packages_password }}
    strategy:
      fail-fast: false
    steps:
      - name: Download arccore build artifact
        uses: actions/download-artifact@v2
        with:
          name: arccore-build-artifact
      - name: Untar arccore build artifact
        shell: bash
        run: |
          tar xf arccore-build-artifact.tar -C /
      - name: Test
        shell: bash
        run: |
          source /env.sh
          cd ${{ env.ARCCORE_BUILD_DIR }}
          ctest ${{ env.CT_OPTS }}

  arcane-test:
    needs:
      - arccon-install
      - arccore-install
      - arcdependencies-install
      - axlstar-install
      - arcane-install
    name: arcane-test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/arcaneframework/rockylinux-foss-2018b-arcane:8-latest
      credentials:
        username: ${{ secrets.ci_ifpen_read_packages_username }}
        password: ${{ secrets.ci_ifpen_read_packages_password }}
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.ARCANE_SOURCE_DIR }}
      - name: Download arcane build artifact
        uses: actions/download-artifact@v2
        with:
          name: arcane-build-artifact
      - name: Untar arcane build artifact
        shell: bash
        run: |
          tar xf arcane-build-artifact.tar -C /
      - name: Download arccore install artifact
        uses: actions/download-artifact@v2
        with:
          name: arccore-install-artifact
      - name: Untar arccore install artifact
        shell: bash
        run: |
          tar xf arccore-install-artifact.tar -C /
      - name: Download axlstar install artifact
        uses: actions/download-artifact@v2
        with:
          name: axlstar-install-artifact
      - name: Untar axlstar install artifact
        shell: bash
        run: |
          tar xf axlstar-install-artifact.tar -C /
      - name: Test
        shell: bash
        run: |
          source /env.sh
          cd ${{ env.ARCANE_BUILD_DIR }}
          ctest ${{ env.CT_OPTS }} --exclude-regex '^mesh_quadratic3d_vtk_4proc$'
