name: Clang Format Checker
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'plugins'
          - 'docs/tutorial'
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: '13'
          check-path: ${{ matrix.path }}
          fallback-style: 'Mozilla' # optional

# See https://github.com/marketplace/actions/clang-format-check for more details