set(ARCANE_SOURCES
  AllCellToAllEnvCellConverter.cc
  AllCellToAllEnvCellConverter.h
  AllEnvData.cc
  ComponentItemInternal.h
  ComponentItem.h
  ComponentItemListBuilder.cc
  ComponentItemVector.h
  ComponentPartItemVectorView.h
  ComponentItemVectorView.h
  ComponentSimd.cc
  ComponentSimd.h
  ComponentConnectivityList.cc
  ComponentItemInternalData.cc
  ConstituentListPrinter.cc
  ComponentModifierWorkInfo.cc
  EnumeratorTracer.cc
  EnumeratorTracer.h
  MaterialsGlobal.cc
  MaterialsGlobal.h
  MaterialModifierOperation.cc
  MatItemVector.h
  EnvItemVector.h
  IncrementalComponentModifier.cc
  MatItemEnumerator.h
  MatVarIndex.h
  MeshComponentData.cc
  MeshComponentPartData.h
  MeshMaterialExchangeMng.cc
  MeshMaterialExchangeMng.h
  MeshMaterialMng.cc
  MeshMaterialModifierImpl.cc
  MeshMaterialVariableIndexer.cc
  MaterialVariableBuildInfo.h
  MeshMaterial.cc
  MeshBlock.cc
  MeshBlock.h
  MeshBlockBuildInfo.cc
  MeshBlockBuildInfo.h
  MeshEnvironment.cc
  MeshEnvironmentBuildInfo.cc
  MeshEnvironmentBuildInfo.h
  MeshMaterialBackup.cc
  MeshMaterialBackup.h
  MeshMaterialInfo.cc
  MeshMaterialInfo.h
  MeshMaterialSynchronizer.cc
  MeshMaterialSynchronizer.h
  MeshMaterialIndirectModifier.cc
  MeshMaterialIndirectModifier.h
  MeshMaterialModifier.cc
  MeshMaterialModifier.h
  MeshMaterialVariable.cc
  MeshMaterialVariable.h
  MeshMaterialVariableDependInfo.cc
  MeshMaterialVariableDependInfo.h
  MeshMaterialVariableRef.h
  MeshMaterialVariableFactoryRegisterer.cc
  MeshMaterialVariableFactoryRegisterer.h
  MeshEnvironmentVariableRef.h
  MeshMaterialVariableScalar.cc
  MeshMaterialVariableArray.cc
  MeshMaterialVariableSynchronizer.cc
  MeshMaterialVariableSynchronizer.h
  MeshMaterialVariableSynchronizerList.cc
  MeshMaterialVariableSynchronizerList.h
  MeshMaterialSynchronizeBuffer.cc
  MeshMaterialVariableFactoryMng.cc
  ComponentItemInternal.h
  ComponentItem.h
  ComponentItemVector.h
  ComponentPartItemVectorView.h
  ComponentItemVectorView.h
  ComponentSimd.h
  EnumeratorTracer.h
  MaterialsGlobal.h
  MatItemVector.h
  EnvItemVector.h
  MatItemEnumerator.h
  MatVarIndex.h
  MeshComponentPartData.h
  MeshMaterialExchangeMng.h
  MaterialVariableBuildInfo.h
  MeshBlock.h
  MeshBlockBuildInfo.h
  MeshEnvironmentBuildInfo.h
  MeshMaterialBackup.h
  MeshMaterialInfo.h
  MeshMaterialSynchronizer.h
  MeshMaterialIndirectModifier.h
  MeshMaterialModifier.h
  MeshMaterialVariable.h
  MeshMaterialVariableDependInfo.h
  MeshMaterialVariableRef.h
  MeshEnvironmentVariableRef.h
  MeshMaterialVariableSynchronizer.h
  MeshMaterialVariableSynchronizerList.h
  CellToAllEnvCellConverter.h
  ComponentItem.h
  MatConcurrency.h
  MatItem.h
  MatCell.h
  MatCellVector.h
  EnvCell.h
  EnvCellVector.h
  MatItemInternal.h
  MeshMaterialVariableComputeFunction.h
  IEnumeratorTracer.h
  IMeshBlock.h
  IMeshComponent.h
  IMeshMaterial.h
  IMeshEnvironment.h
  IMeshMaterialVariableSynchronizer.h
  IMeshMaterialMng.h
  IMeshMaterialVariable.h
  IMeshMaterialVariableComputeFunction.h
  IMeshMaterialSynchronizeBuffer.h
  ItemMaterialVariableBaseT.H

  internal/AllEnvData.h
  internal/ComponentConnectivityList.h
  internal/ComponentItemInternalData.h
  internal/ComponentItemListBuilder.h
  internal/ConstituentListPrinter.h
  internal/ComponentModifierWorkInfo.h
  internal/IncrementalComponentModifier.h
  internal/IMeshMaterialModifierImpl.h
  internal/MaterialModifierOperation.h
  internal/MeshEnvironment.h
  internal/MeshMaterial.h
  internal/MeshMaterialMng.h
  internal/MeshMaterialModifierImpl.h
  internal/MeshMaterialVariablePrivate.h
  internal/MeshComponentData.h
  internal/MeshMaterialVariableIndexer.h
  )
